package br.com.papyrus.view;

import br.com.papyrus.model.CriarConexao;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.ResultSetMetaData;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.table.DefaultTableModel;

/**
 * Esta classe cria uma consulta ao Acervo agrupada por editora
 *
 * @author Alexandre Luiz dos Santos
 * @version 1.0
 */
public class ColtultaAcervoAgrupadaPorEditora extends javax.swing.JInternalFrame {

    public ColtultaAcervoAgrupadaPorEditora() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane2 = new javax.swing.JScrollPane();
        jtContulta = new javax.swing.JTable();
        lblResultado = new javax.swing.JLabel();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        setTitle("CONSULTA ACERVO  AGRUPADA POR EDITORA");
        addInternalFrameListener(new javax.swing.event.InternalFrameListener() {
            public void internalFrameActivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosed(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosing(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeactivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeiconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameIconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameOpened(javax.swing.event.InternalFrameEvent evt) {
                formInternalFrameOpened(evt);
            }
        });

        jtContulta.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Id", "Titulo", "Id", "Autor", "Id", "Editora", "Id", "Classificacao", "Id", "Tipo"
            }
        ));
        jScrollPane2.setViewportView(jtContulta);

        lblResultado.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 1131, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblResultado, javax.swing.GroupLayout.PREFERRED_SIZE, 447, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(21, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 499, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(lblResultado, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(32, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
/**/
    private void formInternalFrameOpened(javax.swing.event.InternalFrameEvent evt) {//GEN-FIRST:event_formInternalFrameOpened
        try {
            Connection conn2 = CriarConexao.abrirConexao();
            String SQL2 = "SELECT COUNT(DISTINCT Editoras_Id) FROM acervo";
            Statement stm2 = conn2.createStatement();
            ResultSet rs2 = stm2.executeQuery(SQL2);

            if (rs2.next()) {
                int resultado = rs2.getInt(1);
                String texto = "Total de Editoras: " + String.valueOf(resultado);
                lblResultado.setText(texto);
            }

            Connection conn = CriarConexao.abrirConexao();
            String SQL = "SELECT ace.Id, ace.Titulo, aut.Id, aut.nome AS Autor, "
                    + "edi.Id, edi.Nome AS Editoras, cla.Id, cla.Nome AS Classificacao, "
                    + "tip.Id, tip.Nome AS Tipo FROM acervo AS ace "
                    + "JOIN autores aut ON aut.id = ace.Autores_Id "
                    + "JOIN editoras edi ON edi.Id = ace.Editoras_Id "
                    + "JOIN classificacoes cla ON cla.Id = ace.Classificacao_Id "
                    + "JOIN tipos tip ON tip.Id = ace.Tipos_Id "
                    + "ORDER BY edi.nome";
            PreparedStatement pstm = conn.prepareStatement(SQL);
            ResultSet rs = pstm.executeQuery(SQL);
            ResultSetMetaData rsm = rs.getMetaData();

            ArrayList<Object[]> data = new ArrayList<>();
            while (rs.next()) {
                Object[] rows = new Object[rsm.getColumnCount()];
                for (int i = 0; i < rows.length; i++) {
                    rows[i] = rs.getObject(i + 1);
                }
                data.add(rows);
            }
            DefaultTableModel dtm = (DefaultTableModel) this.jtContulta.getModel();
            for (int i = 0; i < data.size(); i++) {
                dtm.addRow(data.get(i));
            }
        } catch (ClassNotFoundException | SQLException ex) {
            Logger.getLogger(ColtultaAcervoAgrupadaPorEditora.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_formInternalFrameOpened


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jtContulta;
    private javax.swing.JLabel lblResultado;
    // End of variables declaration//GEN-END:variables
}
