package br.com.papyrus.view;

import br.com.caelum.stella.format.CPFFormatter;
import br.com.caelum.stella.validation.CPFValidator;
import br.com.caelum.stella.validation.InvalidStateException;
import br.com.papyrus.controller.StringLimitada;
import java.awt.Color;
import java.awt.event.KeyEvent;
import javax.swing.JButton;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.JTextField;
import javax.swing.table.AbstractTableModel;

/**
 * Classe que cria e gerencia a tela para Leitores. O Campo CPF tem métodos e
 * propriedades vinCuladas a ele, é utilizado o médoto apenasNumeros que limita
 * a digitação apenas a numeros. CPFValidator que valida o CPF. CPFFormatter que
 * formata o CPF. E no atributo Código - Código de Pré-inicialização é chamada a
 * classe StringLimitada que limita a digitação a 14 digitos, sendo que 11 são
 * para os números e 3 para os separadores.
 *
 * @author Alexandre Luiz dos Santos
 */
public class ViewLeitores extends javax.swing.JInternalFrame {

    public ViewLeitores() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bntAlterar = new javax.swing.JButton();
        btnSalvar = new javax.swing.JButton();
        bntExcluir = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbLeitores = new javax.swing.JTable();
        btnFechar = new javax.swing.JButton();
        lblId = new javax.swing.JLabel();
        lblNome = new javax.swing.JLabel();
        txtId = new javax.swing.JTextField();
        txtNome = new javax.swing.JTextField();
        lnlNomeSocial = new javax.swing.JLabel();
        txtNomeSocial = new javax.swing.JTextField();
        lblSexo = new javax.swing.JLabel();
        txtSexo = new javax.swing.JTextField();
        lblNascimento = new javax.swing.JLabel();
        lblMatricula = new javax.swing.JLabel();
        txtMatricula = new javax.swing.JTextField();
        lblTurma = new javax.swing.JLabel();
        txtTurma = new javax.swing.JTextField();
        lblTurno = new javax.swing.JLabel();
        txtTurno = new javax.swing.JTextField();
        lblCadastro = new javax.swing.JLabel();
        lblPai = new javax.swing.JLabel();
        txtPai = new javax.swing.JTextField();
        lblMae = new javax.swing.JLabel();
        txtMae = new javax.swing.JTextField();
        lblIdentidade = new javax.swing.JLabel();
        txtIdentidade = new javax.swing.JTextField();
        lblCPF = new javax.swing.JLabel();
        lblTelefone = new javax.swing.JLabel();
        txtTelefone = new javax.swing.JTextField();
        lblEmail = new javax.swing.JLabel();
        txtEmail = new javax.swing.JTextField();
        lblEndereco = new javax.swing.JLabel();
        txtEndereco = new javax.swing.JTextField();
        lblBairro = new javax.swing.JLabel();
        txtBairro = new javax.swing.JTextField();
        lblCidade = new javax.swing.JLabel();
        txtCidade = new javax.swing.JTextField();
        lblEstado = new javax.swing.JLabel();
        txtEstado = new javax.swing.JTextField();
        lblReferencia = new javax.swing.JLabel();
        txtReferencia = new javax.swing.JTextField();
        lblObservacoes = new javax.swing.JLabel();
        txtObservacoes = new javax.swing.JTextField();
        txtCadastro = new javax.swing.JFormattedTextField();
        txtNascimento = new javax.swing.JFormattedTextField();
        txtCPF = new javax.swing.JTextField();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        setTitle("Leitores");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        bntAlterar.setText("Alterar");
        getContentPane().add(bntAlterar, new org.netbeans.lib.awtextra.AbsoluteConstraints(109, 533, -1, -1));

        btnSalvar.setText("Salvar");
        getContentPane().add(btnSalvar, new org.netbeans.lib.awtextra.AbsoluteConstraints(28, 533, -1, -1));

        bntExcluir.setText("Excluir");
        getContentPane().add(bntExcluir, new org.netbeans.lib.awtextra.AbsoluteConstraints(194, 533, -1, -1));

        tbLeitores.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tbLeitores);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(28, 345, 1111, 170));

        btnFechar.setText("Fechar");
        btnFechar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFecharActionPerformed(evt);
            }
        });
        getContentPane().add(btnFechar, new org.netbeans.lib.awtextra.AbsoluteConstraints(275, 533, -1, -1));

        lblId.setText("Código");
        lblId.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        getContentPane().add(lblId, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, 50, 20));

        lblNome.setText("Nome");
        lblNome.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        getContentPane().add(lblNome, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 50, 40, 20));

        txtId.setEditable(false);
        getContentPane().add(txtId, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 20, 50, -1));

        txtNome.setDocument(new StringLimitada(45));
        getContentPane().add(txtNome, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 50, 500, -1));

        lnlNomeSocial.setText("Nome Social");
        lnlNomeSocial.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        getContentPane().add(lnlNomeSocial, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 80, 80, 20));

        txtNomeSocial.setDocument(new StringLimitada(45));
        getContentPane().add(txtNomeSocial, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 80, 460, -1));

        lblSexo.setText("Sexo");
        lblSexo.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        getContentPane().add(lblSexo, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 130, 40, 20));

        txtSexo.setDocument(new StringLimitada(1));
        getContentPane().add(txtSexo, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 130, 50, -1));

        lblNascimento.setText("Nascimento");
        lblNascimento.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        getContentPane().add(lblNascimento, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 130, 70, 20));

        lblMatricula.setText("Matricula");
        lblMatricula.setToolTipText("");
        lblMatricula.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        getContentPane().add(lblMatricula, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 130, 50, 20));

        txtMatricula.setDocument(new StringLimitada(10));
        getContentPane().add(txtMatricula, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 130, 120, -1));

        lblTurma.setText("Turma");
        lblTurma.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        getContentPane().add(lblTurma, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 160, 40, 20));

        txtTurma.setDocument(new StringLimitada(4));
        getContentPane().add(txtTurma, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 160, 50, -1));

        lblTurno.setText("Turno");
        lblTurno.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        getContentPane().add(lblTurno, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 160, 60, 20));

        txtTurno.setDocument(new StringLimitada(9));
        getContentPane().add(txtTurno, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 160, 90, -1));

        lblCadastro.setText("Cadastro");
        lblCadastro.setToolTipText("");
        lblCadastro.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        getContentPane().add(lblCadastro, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 160, 60, 20));

        lblPai.setText("Pai");
        lblPai.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        getContentPane().add(lblPai, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 220, 40, 20));

        txtPai.setDocument(new StringLimitada(45));
        getContentPane().add(txtPai, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 220, 500, -1));

        lblMae.setText("Mãe");
        getContentPane().add(lblMae, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 250, -1, 20));

        txtMae.setDocument(new StringLimitada(45));
        getContentPane().add(txtMae, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 250, 500, -1));

        lblIdentidade.setText("Identidade");
        lblIdentidade.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        getContentPane().add(lblIdentidade, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 280, 60, 20));

        txtIdentidade.setDocument(new StringLimitada(15));
        getContentPane().add(txtIdentidade, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 280, 170, -1));

        lblCPF.setText("CPF");
        lblCPF.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        getContentPane().add(lblCPF, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 280, 40, 20));

        lblTelefone.setText("Telefone");
        lblTelefone.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        getContentPane().add(lblTelefone, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 50, 50, 20));

        txtTelefone.setDocument(new StringLimitada(11));
        getContentPane().add(txtTelefone, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 50, 140, -1));

        lblEmail.setText("E-mail");
        lblEmail.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        getContentPane().add(lblEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 50, 40, 20));

        txtEmail.setDocument(new StringLimitada(45));
        getContentPane().add(txtEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(870, 50, 270, -1));

        lblEndereco.setText("Endereço");
        lblEndereco.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        getContentPane().add(lblEndereco, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 100, 60, 20));

        txtEndereco.setDocument(new StringLimitada(50));
        getContentPane().add(txtEndereco, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 100, 480, -1));

        lblBairro.setText("Bairro");
        lblBairro.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        getContentPane().add(lblBairro, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 130, 50, 20));

        txtBairro.setDocument(new StringLimitada(30));
        getContentPane().add(txtBairro, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 130, 480, -1));

        lblCidade.setText("Cidade");
        lblCidade.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        getContentPane().add(lblCidade, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 160, 50, 20));

        txtCidade.setDocument(new StringLimitada(45));
        getContentPane().add(txtCidade, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 160, 480, -1));

        lblEstado.setText("Estado");
        lblEstado.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        getContentPane().add(lblEstado, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 190, 50, 20));

        txtEstado.setDocument(new StringLimitada(2));
        getContentPane().add(txtEstado, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 190, 40, -1));

        lblReferencia.setText("Referencia");
        lblReferencia.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        getContentPane().add(lblReferencia, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 190, 60, 20));

        txtReferencia.setDocument(new StringLimitada(45));
        getContentPane().add(txtReferencia, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 190, 350, -1));

        lblObservacoes.setText("Observações");
        lblObservacoes.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        getContentPane().add(lblObservacoes, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 250, 80, 50));

        txtObservacoes.setDocument(new StringLimitada(45));
        txtObservacoes.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        getContentPane().add(txtObservacoes, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 250, 450, 50));

        txtCadastro.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.DateFormatter(new java.text.SimpleDateFormat("yyyy/MM/dd"))));
        txtCadastro.setToolTipText("Data do cadastramento. Formato AAAA/MM/DD (Ano, Mês, Dia).");
        getContentPane().add(txtCadastro, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 160, 120, -1));

        txtNascimento.setToolTipText("Data de nascimento. Formato AAAA/MM/DD (Ano, Mês, Dia).");
        getContentPane().add(txtNascimento, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 130, 90, -1));

        txtCPF.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtCPFFocusLost(evt);
            }
        });
        getContentPane().add(txtCPF, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 280, 220, -1));

        setBounds(0, 0, 1183, 631);
    }// </editor-fold>//GEN-END:initComponents

    private void btnFecharActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFecharActionPerformed
        // Exibe janela perguntando se deseja sair da tela autores
        int sair = JOptionPane.showConfirmDialog(null, "Tem certeza que deseja fechar o formulário ?", "Aviso", JOptionPane.YES_NO_OPTION);
        if (sair == JOptionPane.YES_OPTION) {
            this.dispose();
        }
    }//GEN-LAST:event_btnFecharActionPerformed

    private void txtCPFFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtCPFFocusLost
        String cpf = txtCPF.getText();
        CPFValidator validador = new CPFValidator();
        CPFFormatter formatadorCPF = new CPFFormatter();
        try {
            validador.assertValid(cpf);
            txtCPF.setText(formatadorCPF.format(cpf));
        } catch (InvalidStateException e) {
            JOptionPane.showMessageDialog(null, "CPF " + cpf + " inválido!");
            txtCPF.setText("");
        }
    }//GEN-LAST:event_txtCPFFocusLost


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bntAlterar;
    private javax.swing.JButton bntExcluir;
    private javax.swing.JButton btnFechar;
    public javax.swing.JButton btnSalvar;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblBairro;
    private javax.swing.JLabel lblCPF;
    private javax.swing.JLabel lblCadastro;
    private javax.swing.JLabel lblCidade;
    private javax.swing.JLabel lblEmail;
    private javax.swing.JLabel lblEndereco;
    private javax.swing.JLabel lblEstado;
    private javax.swing.JLabel lblId;
    private javax.swing.JLabel lblIdentidade;
    private javax.swing.JLabel lblMae;
    private javax.swing.JLabel lblMatricula;
    private javax.swing.JLabel lblNascimento;
    private javax.swing.JLabel lblNome;
    private javax.swing.JLabel lblObservacoes;
    private javax.swing.JLabel lblPai;
    private javax.swing.JLabel lblReferencia;
    private javax.swing.JLabel lblSexo;
    private javax.swing.JLabel lblTelefone;
    private javax.swing.JLabel lblTurma;
    private javax.swing.JLabel lblTurno;
    private javax.swing.JLabel lnlNomeSocial;
    private javax.swing.JTable tbLeitores;
    private javax.swing.JTextField txtBairro;
    private javax.swing.JTextField txtCPF;
    private javax.swing.JFormattedTextField txtCadastro;
    private javax.swing.JTextField txtCidade;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JTextField txtEndereco;
    private javax.swing.JTextField txtEstado;
    private javax.swing.JTextField txtId;
    private javax.swing.JTextField txtIdentidade;
    private javax.swing.JTextField txtMae;
    private javax.swing.JTextField txtMatricula;
    private javax.swing.JFormattedTextField txtNascimento;
    private javax.swing.JTextField txtNome;
    private javax.swing.JTextField txtNomeSocial;
    private javax.swing.JTextField txtObservacoes;
    private javax.swing.JTextField txtPai;
    private javax.swing.JTextField txtReferencia;
    private javax.swing.JTextField txtSexo;
    private javax.swing.JTextField txtTelefone;
    private javax.swing.JTextField txtTurma;
    private javax.swing.JTextField txtTurno;
    // End of variables declaration//GEN-END:variables

    //GET para os campo e botões do formulário para uso do ControllerLeitores
    public JButton getBtnSalvar() {
        return btnSalvar;
    }

    public JButton getBtnExcluir() {
        return bntExcluir;
    }

    public JButton getBtnAlterar() {
        return bntAlterar;
    }

    public JTable getTbLeitores() {
        return tbLeitores;
    }

    public JTextField getTxtId() {
        return txtId;
    }

    public JTextField getTxtNome() {
        return txtNome;
    }

    public JTextField getTxtNomeSocial() {
        return txtNomeSocial;
    }

    public JTextField getTxtSexo() {
        return txtSexo;
    }

    public JTextField getTxtNascimento() {
        return txtNascimento;
    }

    public JTextField getTxtMatricula() {
        return txtMatricula;
    }

    public JTextField getTxtTurma() {
        return txtTurma;
    }

    public JTextField getTxtTurno() {
        return txtTurno;
    }

    public JTextField getTxtCadastro() {
        return txtCadastro;
    }

    public JTextField getTxtPai() {
        return txtPai;
    }

    public JTextField getTxtMae() {
        return txtMae;
    }

    public JTextField getTxtIdentidade() {
        return txtIdentidade;
    }

    public JTextField getTxtCPF() {
        return txtCPF;
    }

    public JTextField getTxtTelefone() {
        return txtTelefone;
    }

    public JTextField getTxtEmail() {
        return txtEmail;
    }

    public JTextField getTxtEndereco() {
        return txtEndereco;
    }

    public JTextField getTxtBairro() {
        return txtBairro;
    }

    public JTextField getTxtCidade() {
        return txtCidade;
    }

    public JTextField getTxtEstado() {
        return txtEstado;
    }

    public JTextField getTxtReferencia() {
        return txtReferencia;
    }

    public JTextField getTxtObservacoes() {
        return txtObservacoes;
    }

    /**
     * Método que linka o AbstractTableModel a tabela no formulário
     * setTbLeitores
     *
     * @param modelo vindo de ControllerAutores.carregar() com a lista do
     * TableModel
     */
    public void setTbLeitores(AbstractTableModel modelo) {
        this.tbLeitores.setModel(modelo);
        this.tbLeitores.setAutoResizeMode(JTable.AUTO_RESIZE_OFF);
        this.tbLeitores.setSelectionBackground(Color.cyan);  //Põe cor azul na linha atual
        this.tbLeitores.setSelectionForeground(Color.red);   //Põe letras em vermelho
        this.tbLeitores.setBackground(Color.lightGray);      //põe cor de fundo azul
        this.tbLeitores.getColumnModel().getColumn(0).setPreferredWidth(70); //Largura da coluna
        this.tbLeitores.getColumnModel().getColumn(0).setResizable(true);    //Coluna redimenciosavel
        this.tbLeitores.getColumnModel().getColumn(1).setPreferredWidth(200);
        this.tbLeitores.getColumnModel().getColumn(1).setResizable(true);
        this.tbLeitores.getColumnModel().getColumn(2).setPreferredWidth(200);
        this.tbLeitores.getColumnModel().getColumn(2).setResizable(true);
    }

    /**
     * Este método faz com que seja digitado apenas caracteres alfanuméricos.
     *
     * @param evt que é o texto digitado pelo KeyEvent do evento que chama este
     * método.
     */
    public void apenasNumeros(KeyEvent evt) {
        try {
            Integer.parseInt(String.valueOf(evt.getKeyChar()));
        } catch (NumberFormatException err) {
            JOptionPane.showMessageDialog(null, "Informe apenas números!");
            evt.consume();
        }
    }

}
