package br.com.papyrus.view;

import br.com.papyrus.controller.ControllerEmprestimosComboBoxAcervo;
import br.com.papyrus.controller.ControllerEmprestimosComboBoxLeitores;
import br.com.papyrus.controller.StringLimitada;
import br.com.papyrus.model.CriarConexao;
import br.com.papyrus.model.ModelEmprestimosVO;
import static com.sun.org.apache.xalan.internal.lib.ExsltDatetime.date;
import com.toedter.calendar.JDateChooser;
import java.awt.Color;
import static java.lang.String.format;
import static java.lang.String.format;
import java.sql.Connection;
import java.sql.Date;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.text.SimpleDateFormat;
import java.time.LocalDate;
import java.time.format.DateTimeFormatter;
import java.util.Calendar;
import java.util.GregorianCalendar;
import javax.swing.JButton;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.JTextField;
import javax.swing.table.AbstractTableModel;

/**
 * Classe que cria e gerencia a tela para Emprestimos.
 *
 * @author Alexandre Luiz dos Santos
 */
public class ViewEmprestimos extends javax.swing.JInternalFrame {

    ControllerEmprestimosComboBoxLeitores leitores;
    ControllerEmprestimosComboBoxAcervo acervo;

    /**
     * Creates new form ViewAutores
     */
    public ViewEmprestimos() {
        initComponents();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bntAlterar = new javax.swing.JButton();
        lblLeitor = new javax.swing.JLabel();
        txtLeitores_Id = new javax.swing.JTextField();
        lblAcervo = new javax.swing.JLabel();
        txtAcervo_Id = new javax.swing.JTextField();
        btnSalvar = new javax.swing.JButton();
        bntExcluir = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbEmprestimos = new javax.swing.JTable();
        btnFechar = new javax.swing.JButton();
        txtNomeLeitores = new javax.swing.JTextField();
        txtTituloAcervo = new javax.swing.JTextField();
        lblEmprestimo = new javax.swing.JLabel();
        lblDevolucao = new javax.swing.JLabel();
        txtDevolucao = new javax.swing.JTextField();
        lblSubTituloAcervo = new javax.swing.JLabel();
        txtSubTituloAcervo = new javax.swing.JTextField();
        lblExemplarAcervo = new javax.swing.JLabel();
        txtExemplarAcervo = new javax.swing.JTextField();
        lblEdicaoAcervo = new javax.swing.JLabel();
        txtEdicaoAcervo = new javax.swing.JTextField();
        lblVolumeAcervo = new javax.swing.JLabel();
        txtVolumeAcervo = new javax.swing.JTextField();
        lblDisponivelAcervo = new javax.swing.JLabel();
        txtDisponivelAcervo = new javax.swing.JTextField();
        lblLocalAcervo = new javax.swing.JLabel();
        txtLocalAcervo = new javax.swing.JTextField();
        lblTituloDaTela = new javax.swing.JLabel();
        txtEmprestimo = new javax.swing.JTextField();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        setTitle("Emprestimos");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        bntAlterar.setText("Alterar");
        bntAlterar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bntAlterarActionPerformed(evt);
            }
        });
        getContentPane().add(bntAlterar, new org.netbeans.lib.awtextra.AbsoluteConstraints(131, 551, -1, -1));

        lblLeitor.setText("Leitor");
        lblLeitor.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        getContentPane().add(lblLeitor, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 25, 40, -1));

        txtLeitores_Id.setEditable(false);
        txtLeitores_Id.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtLeitores_IdMouseClicked(evt);
            }
        });
        txtLeitores_Id.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtLeitores_IdActionPerformed(evt);
            }
        });
        getContentPane().add(txtLeitores_Id, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 20, 60, -1));

        lblAcervo.setText("Acervo");
        lblAcervo.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        getContentPane().add(lblAcervo, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 20, 40, 20));

        txtAcervo_Id.setDocument(new StringLimitada(45));
        txtAcervo_Id.setEditable(false);
        txtAcervo_Id.setToolTipText("Nome do autor da obra");
        txtAcervo_Id.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtAcervo_IdMouseClicked(evt);
            }
        });
        getContentPane().add(txtAcervo_Id, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 20, 60, -1));

        btnSalvar.setText("Salvar");
        btnSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalvarActionPerformed(evt);
            }
        });
        getContentPane().add(btnSalvar, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 551, -1, -1));

        bntExcluir.setText("Excluir");
        bntExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bntExcluirActionPerformed(evt);
            }
        });
        getContentPane().add(bntExcluir, new org.netbeans.lib.awtextra.AbsoluteConstraints(216, 551, -1, -1));

        tbEmprestimos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tbEmprestimos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbEmprestimosMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tbEmprestimos);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(48, 354, 1100, 160));

        btnFechar.setText("Fechar");
        btnFechar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFecharActionPerformed(evt);
            }
        });
        getContentPane().add(btnFechar, new org.netbeans.lib.awtextra.AbsoluteConstraints(297, 551, -1, -1));

        txtNomeLeitores.setEditable(false);
        getContentPane().add(txtNomeLeitores, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 20, 350, -1));

        txtTituloAcervo.setEditable(false);
        getContentPane().add(txtTituloAcervo, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 20, 450, -1));

        lblEmprestimo.setText("Emprestimo");
        lblEmprestimo.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        getContentPane().add(lblEmprestimo, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 60, 70, 20));

        lblDevolucao.setText("Devolução");
        lblDevolucao.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        getContentPane().add(lblDevolucao, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 60, 60, 20));
        getContentPane().add(txtDevolucao, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 60, 120, -1));

        lblSubTituloAcervo.setText("SubTitulo");
        getContentPane().add(lblSubTituloAcervo, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 60, 60, 20));
        getContentPane().add(txtSubTituloAcervo, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 60, 500, -1));

        lblExemplarAcervo.setText("Exemplar");
        lblExemplarAcervo.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        getContentPane().add(lblExemplarAcervo, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 100, 60, 20));
        getContentPane().add(txtExemplarAcervo, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 100, 110, -1));

        lblEdicaoAcervo.setText("Edição");
        lblEdicaoAcervo.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        getContentPane().add(lblEdicaoAcervo, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 100, 50, 20));

        txtEdicaoAcervo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtEdicaoAcervoActionPerformed(evt);
            }
        });
        getContentPane().add(txtEdicaoAcervo, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 100, 120, -1));

        lblVolumeAcervo.setText("Volume");
        lblVolumeAcervo.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        getContentPane().add(lblVolumeAcervo, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 100, 50, 20));
        getContentPane().add(txtVolumeAcervo, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 100, 110, -1));

        lblDisponivelAcervo.setText("Disponivel");
        lblDisponivelAcervo.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        getContentPane().add(lblDisponivelAcervo, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 100, 60, 20));
        getContentPane().add(txtDisponivelAcervo, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 100, 110, -1));

        lblLocalAcervo.setText("Local");
        lblLocalAcervo.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        getContentPane().add(lblLocalAcervo, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 140, 40, 20));

        txtLocalAcervo.setToolTipText("Local onde o acervo está guardado fisicamente.");
        getContentPane().add(txtLocalAcervo, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 140, 1050, 30));

        lblTituloDaTela.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lblTituloDaTela.setText("ITENS DISPONÍVEIS PARA EMPRÉSTIMO");
        getContentPane().add(lblTituloDaTela, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 240, 460, 20));

        txtEmprestimo.setEditable(false);
        getContentPane().add(txtEmprestimo, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 60, 110, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bntAlterarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bntAlterarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bntAlterarActionPerformed

    private void txtLeitores_IdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtLeitores_IdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtLeitores_IdActionPerformed

    private void btnSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalvarActionPerformed

    }//GEN-LAST:event_btnSalvarActionPerformed

    private void btnFecharActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFecharActionPerformed
        // Exibe janela perguntando se deseja sair da tela autores
        int sair = JOptionPane.showConfirmDialog(null, "Tem certeza que deseja fechar o formulário ?", "Aviso", JOptionPane.YES_NO_OPTION);
        if (sair == JOptionPane.YES_OPTION) {
            this.dispose();
        }
    }//GEN-LAST:event_btnFecharActionPerformed

    private void bntExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bntExcluirActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bntExcluirActionPerformed

    private void tbEmprestimosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbEmprestimosMouseClicked

    }//GEN-LAST:event_tbEmprestimosMouseClicked

    private void txtEdicaoAcervoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtEdicaoAcervoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtEdicaoAcervoActionPerformed

    private void txtLeitores_IdMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtLeitores_IdMouseClicked
        if (leitores == null) {
            leitores = new ControllerEmprestimosComboBoxLeitores();
            leitores.setVisible(true);
        } else {
            leitores.setVisible(true);
            leitores.setState(JFrame.NORMAL);
        }
    }//GEN-LAST:event_txtLeitores_IdMouseClicked

    private void txtAcervo_IdMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtAcervo_IdMouseClicked
        if (acervo == null) {
            acervo = new ControllerEmprestimosComboBoxAcervo();
            acervo.setVisible(true);
        } else {
            acervo.setVisible(true);
            acervo.setState(JFrame.NORMAL);
        }

    }//GEN-LAST:event_txtAcervo_IdMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bntAlterar;
    private javax.swing.JButton bntExcluir;
    private javax.swing.JButton btnFechar;
    public javax.swing.JButton btnSalvar;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblAcervo;
    private javax.swing.JLabel lblDevolucao;
    private javax.swing.JLabel lblDisponivelAcervo;
    private javax.swing.JLabel lblEdicaoAcervo;
    private javax.swing.JLabel lblEmprestimo;
    private javax.swing.JLabel lblExemplarAcervo;
    private javax.swing.JLabel lblLeitor;
    private javax.swing.JLabel lblLocalAcervo;
    private javax.swing.JLabel lblSubTituloAcervo;
    private javax.swing.JLabel lblTituloDaTela;
    private javax.swing.JLabel lblVolumeAcervo;
    private javax.swing.JTable tbEmprestimos;
    public static javax.swing.JTextField txtAcervo_Id;
    public static javax.swing.JTextField txtDevolucao;
    public static javax.swing.JTextField txtDisponivelAcervo;
    public static javax.swing.JTextField txtEdicaoAcervo;
    public static javax.swing.JTextField txtEmprestimo;
    public static javax.swing.JTextField txtExemplarAcervo;
    public static javax.swing.JTextField txtLeitores_Id;
    public static javax.swing.JTextField txtLocalAcervo;
    public static javax.swing.JTextField txtNomeLeitores;
    public static javax.swing.JTextField txtSubTituloAcervo;
    public static javax.swing.JTextField txtTituloAcervo;
    public static javax.swing.JTextField txtVolumeAcervo;
    // End of variables declaration//GEN-END:variables

    ////////////////////////////////  ATENÇÃO  ////////////////////////////////
    //GET para os campo e botões do formulário para uso do ControllerEmprestimos
    ////////////////////////////////  ATENÇÃO  ////////////////////////////////
    public JButton getBtnSalvar() {
        return btnSalvar;
    }

    public JButton getBtnExcluir() {
        return bntExcluir;
    }

    public JButton getBtnAlterar() {
        return bntAlterar;
    }

    public JTextField getTxtLeitores_Id() {
        return txtLeitores_Id;
    }

    public JTextField getTxtAcervo_Id() {
        return txtAcervo_Id;
    }
    public JTextField getTxtEmprestimo() {
        return txtEmprestimo;
    }

    public JTextField getTxtDevolucao() {
        return txtDevolucao;
    }

    public JTextField getTxtNomeLeitores() {
        return txtNomeLeitores;
    }

    public JTextField getTxtTituloAcervo() {
        return txtTituloAcervo;
    }

    public JTextField getTxtSubTituloAcervo() {
        return txtSubTituloAcervo;
    }

    public JTextField getTxtExemplarAcervo() {
        return txtExemplarAcervo;
    }

    public JTextField getTxtEdicaoAcervo() {
        return txtEdicaoAcervo;
    }

    public JTextField getTxtVolumeAcervo() {
        return txtVolumeAcervo;
    }

    public JTextField getTxtLocalAcervo() {
        return txtLocalAcervo;
    }

    public JTextField getTxtDisponivelAcervo() {
        return txtDisponivelAcervo;
    }

    public JTable getTbEmprestimos() {
        return tbEmprestimos;
    }

    /**
     * Método que linka o AbstractTableModel a tabela no formulário
     * setTbEmprestimos
     *
     * @param modelo vindo de ControllerEmprestimos.carregar() com a lista do
     * TableModel
     */
    public void setTbEmprestimos(AbstractTableModel modelo) {
        this.tbEmprestimos.setModel(modelo);
        this.tbEmprestimos.setAutoResizeMode(JTable.AUTO_RESIZE_OFF);
        this.tbEmprestimos.setSelectionBackground(Color.cyan);  //Põe cor azul na linha atual
        this.tbEmprestimos.setSelectionForeground(Color.red);   //Põe letras em vermelho
        this.tbEmprestimos.setBackground(Color.lightGray);      //põe cor de fundo azul
        this.tbEmprestimos.getColumnModel().getColumn(0).setPreferredWidth(70); //Largura da coluna
        this.tbEmprestimos.getColumnModel().getColumn(0).setResizable(true);    //Coluna redimenciosavel
        this.tbEmprestimos.getColumnModel().getColumn(1).setPreferredWidth(200);
        this.tbEmprestimos.getColumnModel().getColumn(1).setResizable(true);
        this.tbEmprestimos.getColumnModel().getColumn(2).setPreferredWidth(200);
        this.tbEmprestimos.getColumnModel().getColumn(2).setResizable(true);
        this.tbEmprestimos.getColumnModel().getColumn(3).setPreferredWidth(60);
        this.tbEmprestimos.getColumnModel().getColumn(3).setResizable(true);
        this.tbEmprestimos.getColumnModel().getColumn(4).setPreferredWidth(60);
        this.tbEmprestimos.getColumnModel().getColumn(4).setResizable(true);
        this.tbEmprestimos.getColumnModel().getColumn(5).setPreferredWidth(60);
        this.tbEmprestimos.getColumnModel().getColumn(5).setResizable(true);
        this.tbEmprestimos.getColumnModel().getColumn(6).setPreferredWidth(150);
        this.tbEmprestimos.getColumnModel().getColumn(6).setResizable(true);
        this.tbEmprestimos.getColumnModel().getColumn(7).setPreferredWidth(80);
        this.tbEmprestimos.getColumnModel().getColumn(7).setResizable(true);
    }
}
