package br.com.papyrus.view;

import br.com.papyrus.controller.ControllerAcervo;
import br.com.papyrus.model.CriarConexao;
import br.com.papyrus.model.ModelClassificacoesComboVO;
import br.com.papyrus.model.ModelClassificacoesVO;
import br.com.papyrus.model.ModelEditorasComboVO;
import br.com.papyrus.model.ModelEditorasDAO;
import br.com.papyrus.model.ModelEditorasVO;
import java.awt.Color;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.HashMap;
import java.util.logging.Level;
import java.util.logging.Logger;
import javafx.beans.binding.Bindings;
import javax.swing.JButton;
import javax.swing.JFormattedTextField;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.JTextField;
import javax.swing.table.AbstractTableModel;

/**
 * Classe que cria e gerencia a tela para Acervo.
 *
 * @author Alexandre Luiz dos Santos
 */
public class ViewAcervo extends javax.swing.JInternalFrame {

    /**
     * Creates new form ViewAutores
     */
    public ViewAcervo() {
        initComponents();
        PopularComboEditora();
        PopularComboClassificacao();
        PopularComboTipo();
        txtIdioma.setVisible(false);
        txtDisponivel.setVisible(false);
    }

    /**
     * Método que leva os dados da tabela Tipos para o combobox
     */
    public void PopularComboTipo() {
        CriarConexao cc = new CriarConexao();
        HashMap<String, Integer> mapTipos = cc.CarregarTipos();
        for (String s : mapTipos.keySet()) {
            cmbTipo.addItem(s);
        }
    }

    /**
     * Método que leva os dados da Editora para o combobox
     */
    public void PopularComboClassificacao() {
        CriarConexao cc = new CriarConexao();
        HashMap<String, Integer> mapClassificacoes = cc.CarregarClassificacoes();
        for (String s : mapClassificacoes.keySet()) {
            cmbClassificacao.addItem(s);

        }
    }

    /**
     * Método que leva os dados da Editora para o combobox
     */
    public void PopularComboEditora() {
        CriarConexao cc = new CriarConexao();
        HashMap<String, Integer> mapEditoras = cc.CarregarEditoras();
        for (String s : mapEditoras.keySet()) {
            cmbEditora.addItem(s);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        entityManager = java.beans.Beans.isDesignTime() ? null : javax.persistence.Persistence.createEntityManagerFactory("papyrus?zeroDateTimeBehavior=convertToNullPU").createEntityManager();
        editorasQuery = java.beans.Beans.isDesignTime() ? null : entityManager.createQuery("SELECT e FROM Editoras e");
        editorasList = java.beans.Beans.isDesignTime() ? java.util.Collections.emptyList() : editorasQuery.getResultList();
        bntAlterar = new javax.swing.JButton();
        btnSalvar = new javax.swing.JButton();
        bntExcluir = new javax.swing.JButton();
        jScrollPaneAcervo = new javax.swing.JScrollPane();
        tbACervo = new javax.swing.JTable();
        btnFechar = new javax.swing.JButton();
        lblId = new javax.swing.JLabel();
        lblTitulo = new javax.swing.JLabel();
        lblSubTitulo = new javax.swing.JLabel();
        lblSerie = new javax.swing.JLabel();
        lblExemplar = new javax.swing.JLabel();
        lblEdicao = new javax.swing.JLabel();
        lblPaginas = new javax.swing.JLabel();
        lblVolume = new javax.swing.JLabel();
        lblAno = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        lblIdioma = new javax.swing.JLabel();
        lblEditora = new javax.swing.JLabel();
        cmbEditora = new javax.swing.JComboBox<>();
        lblClassificacao = new javax.swing.JLabel();
        lblTipo = new javax.swing.JLabel();
        cmbClassificacao = new javax.swing.JComboBox<>();
        cmbTipo = new javax.swing.JComboBox<>();
        lblTombo = new javax.swing.JLabel();
        lblCDU = new javax.swing.JLabel();
        lblCDD = new javax.swing.JLabel();
        lblCUTTER = new javax.swing.JLabel();
        lblISBN = new javax.swing.JLabel();
        lblObservacoes = new javax.swing.JLabel();
        cmbDisponivel = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        txtId = new javax.swing.JTextField();
        txtTitulo = new javax.swing.JTextField();
        txtSubTitulo = new javax.swing.JTextField();
        txtSerie = new javax.swing.JTextField();
        cmbIdioma = new javax.swing.JComboBox<>();
        txtExemplar = new javax.swing.JTextField();
        txtEdicao = new javax.swing.JTextField();
        txtPaginas = new javax.swing.JTextField();
        txtVolume = new javax.swing.JTextField();
        txtAno = new javax.swing.JTextField();
        txtAquisicao = new javax.swing.JFormattedTextField();
        txtLocal = new javax.swing.JTextField();
        txtTombo = new javax.swing.JTextField();
        txtCDU = new javax.swing.JTextField();
        txtCDD = new javax.swing.JTextField();
        txtCUTTER = new javax.swing.JTextField();
        txtISBN = new javax.swing.JTextField();
        txtObservacoes = new javax.swing.JTextField();
        txtEditoras_Id = new javax.swing.JTextField();
        txtClassificacao_Id = new javax.swing.JTextField();
        txtTipos_Id = new javax.swing.JTextField();
        txtIdioma = new javax.swing.JTextField();
        txtDisponivel = new javax.swing.JTextField();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        setTitle("Acervo");

        bntAlterar.setText("Alterar");
        bntAlterar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bntAlterarActionPerformed(evt);
            }
        });

        btnSalvar.setText("Salvar");
        btnSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalvarActionPerformed(evt);
            }
        });

        bntExcluir.setText("Excluir");
        bntExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bntExcluirActionPerformed(evt);
            }
        });

        tbACervo.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tbACervo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbACervoMouseClicked(evt);
            }
        });
        jScrollPaneAcervo.setViewportView(tbACervo);

        btnFechar.setText("Fechar");
        btnFechar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFecharActionPerformed(evt);
            }
        });

        lblId.setText("Código");

        lblTitulo.setText("Título");

        lblSubTitulo.setText("Subtítulo");

        lblSerie.setText("Série");

        lblExemplar.setText("Exemplar");

        lblEdicao.setText("Edição");

        lblPaginas.setText("Páginas");

        lblVolume.setText("Volume");

        lblAno.setText("Ano");

        jLabel1.setText("Aquisição");

        jLabel2.setText("Local");

        lblIdioma.setText("Idioma");

        lblEditora.setText("Editora");

        cmbEditora.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbEditoraActionPerformed(evt);
            }
        });

        lblClassificacao.setText("Classificação");

        lblTipo.setText("Tipo");

        cmbClassificacao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbClassificacaoActionPerformed(evt);
            }
        });

        cmbTipo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbTipoActionPerformed(evt);
            }
        });

        lblTombo.setText("Tombo");

        lblCDU.setText("CDU");

        lblCDD.setText("CDD");

        lblCUTTER.setText("CUTTER");

        lblISBN.setText("ISBN");

        lblObservacoes.setText("Observações");

        cmbDisponivel.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Sim", "Não" }));
        cmbDisponivel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbDisponivelActionPerformed(evt);
            }
        });

        jLabel3.setText("Disponivel");

        txtId.setEditable(false);

        txtTitulo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTituloActionPerformed(evt);
            }
        });

        txtSerie.setToolTipText("Se pertence a uma serie, Exemplo: Harry potter.");

        cmbIdioma.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Alemão", "Árabe", "Bengali", "Chinês", "Coreano", "Espanhol", "Francês", "Hindi", "Inglês", "Italiano", "Japonês", "Javanês", "Marati", "Português", "Russo", "Tâmil", "Telugo", "Turco", "Urdu", "Vietnamita" }));
        cmbIdioma.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbIdiomaActionPerformed(evt);
            }
        });

        txtAno.setToolTipText("Ano da edição da obra");

        txtAquisicao.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.DateFormatter(new java.text.SimpleDateFormat("yyyy/MM/dd"))));
        txtAquisicao.setToolTipText("Data de aquisição da obra");

        txtLocal.setToolTipText("Local onde o item está guardado.");

        txtTombo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTomboActionPerformed(evt);
            }
        });

        txtCDU.setToolTipText("Classificação Decimal Universal");

        txtCDD.setToolTipText("Classificação Decimal Dewey");

        txtCUTTER.setToolTipText("Indicam a autoria de uma obra literária.");

        txtObservacoes.setToolTipText("Observações a respeito da obra.");

        txtTipos_Id.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTipos_IdActionPerformed(evt);
            }
        });

        txtIdioma.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtIdiomaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblEditora)
                                    .addComponent(lblTipo)
                                    .addComponent(lblClassificacao))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtEditoras_Id)
                                    .addComponent(txtClassificacao_Id)
                                    .addComponent(txtTipos_Id))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(cmbClassificacao, javax.swing.GroupLayout.Alignment.TRAILING, 0, 433, Short.MAX_VALUE)
                                    .addComponent(cmbEditora, javax.swing.GroupLayout.Alignment.TRAILING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(cmbTipo, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                    .addComponent(lblSerie)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(txtSerie, javax.swing.GroupLayout.PREFERRED_SIZE, 313, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 34, Short.MAX_VALUE)
                                    .addComponent(lblIdioma, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(cmbIdioma, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                    .addComponent(lblSubTitulo)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(txtSubTitulo))
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                    .addComponent(lblTitulo)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(txtTitulo))
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                    .addComponent(lblId)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(txtId, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(54, 54, 54)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txtLocal))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(lblVolume)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(txtVolume))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(lblExemplar)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(txtExemplar, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(lblTombo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(lblCUTTER, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(txtTombo)
                                            .addComponent(txtCUTTER, javax.swing.GroupLayout.DEFAULT_SIZE, 107, Short.MAX_VALUE))))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(41, 41, 41)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(lblAno)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(txtAno))
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(lblEdicao)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(txtEdicao, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(lblISBN)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(txtISBN))
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(lblCDU)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(txtCDU, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                        .addGap(33, 33, 33)))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(lblCDD)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(txtCDD, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel1)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(txtAquisicao, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(lblPaginas)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(txtPaginas, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(cmbDisponivel, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(34, 34, 34))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(txtIdioma, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(txtDisponivel, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblObservacoes)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtObservacoes, javax.swing.GroupLayout.PREFERRED_SIZE, 942, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPaneAcervo)
                        .addGap(34, 34, 34))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnSalvar)
                        .addGap(18, 18, 18)
                        .addComponent(bntAlterar)
                        .addGap(20, 20, 20)
                        .addComponent(bntExcluir)
                        .addGap(18, 18, 18)
                        .addComponent(btnFechar)
                        .addContainerGap(932, Short.MAX_VALUE))))
        );

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {lblId, lblSerie, lblSubTitulo, lblTitulo});

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {jLabel2, lblCUTTER, lblExemplar, lblTombo, lblVolume});

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {lblAno, lblEdicao});

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {jLabel1, lblPaginas});

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {lblCDU, lblISBN});

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {lblClassificacao, lblEditora, lblTipo});

        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblId)
                    .addComponent(lblExemplar)
                    .addComponent(lblEdicao)
                    .addComponent(lblPaginas)
                    .addComponent(txtId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtExemplar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtEdicao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtPaginas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblTitulo)
                    .addComponent(lblVolume)
                    .addComponent(lblAno)
                    .addComponent(jLabel1)
                    .addComponent(txtTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtVolume, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtAno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtAquisicao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblSubTitulo)
                    .addComponent(jLabel2)
                    .addComponent(txtSubTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtLocal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblSerie)
                    .addComponent(lblIdioma)
                    .addComponent(txtSerie, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cmbIdioma, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblEditora)
                            .addComponent(txtEditoras_Id, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(10, 10, 10)
                        .addComponent(lblClassificacao)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lblTipo))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cmbEditora, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblTombo)
                            .addComponent(lblCDU)
                            .addComponent(lblCDD)
                            .addComponent(txtTombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtCDU, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtCDD, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cmbClassificacao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblCUTTER)
                            .addComponent(lblISBN)
                            .addComponent(txtCUTTER, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtISBN, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtClassificacao_Id, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cmbTipo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtTipos_Id, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lblObservacoes)
                        .addComponent(txtObservacoes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(cmbDisponivel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtIdioma, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtDisponivel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPaneAcervo, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSalvar)
                    .addComponent(bntExcluir)
                    .addComponent(bntAlterar)
                    .addComponent(btnFechar))
                .addContainerGap(37, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bntAlterarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bntAlterarActionPerformed
    }//GEN-LAST:event_bntAlterarActionPerformed

    private void btnSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalvarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnSalvarActionPerformed

    private void btnFecharActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFecharActionPerformed
        // Exibe janela perguntando se deseja sair da tela autores
        int sair = JOptionPane.showConfirmDialog(null, "Tem certeza que deseja fechar o formulário ?", "Aviso", JOptionPane.YES_NO_OPTION);
        if (sair == JOptionPane.YES_OPTION) {
            this.dispose();
        }
    }//GEN-LAST:event_btnFecharActionPerformed

    private void bntExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bntExcluirActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bntExcluirActionPerformed

    private void tbACervoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbACervoMouseClicked

    }//GEN-LAST:event_tbACervoMouseClicked

    private void txtTituloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTituloActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTituloActionPerformed

    private void txtTomboActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTomboActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTomboActionPerformed

    private void cmbEditoraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbEditoraActionPerformed
        CriarConexao cc = new CriarConexao();
        HashMap<String, Integer> mapEditoras = cc.CarregarEditoras();
        //txtEditoras_Id.setText(mapEditoras.get(cmbEditora.getSelectedItem().toString()).toString());
        txtEditoras_Id.setText(mapEditoras.get(cmbEditora.getSelectedItem().toString()).toString());
        // O primeiro toString() retorna o nome da Editora, o segundo o código
        // Ou seja o primeiro retorna o primeiro campo e o segundo o segundo campo no Combobox
    }//GEN-LAST:event_cmbEditoraActionPerformed


    private void cmbClassificacaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbClassificacaoActionPerformed
        CriarConexao cc = new CriarConexao();
        HashMap<String, Integer> mapClassificacoes = cc.CarregarClassificacoes();
        txtClassificacao_Id.setText(mapClassificacoes.get(cmbClassificacao.getSelectedItem().toString()).toString());
    }//GEN-LAST:event_cmbClassificacaoActionPerformed

    private void cmbTipoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbTipoActionPerformed
        CriarConexao cc = new CriarConexao();
        HashMap<String, Integer> mapTipos = cc.CarregarTipos();
        txtTipos_Id.setText((mapTipos.get(cmbTipo.getSelectedItem().toString()).toString()));
        // O primeiro toString() retorna o nome da Editora, o segundo o código
        // Ou seja o primeiro retorna o primeiro campo e o segundo o segundo campo no Combobox
    }//GEN-LAST:event_cmbTipoActionPerformed

    private void txtIdiomaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtIdiomaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtIdiomaActionPerformed

    private void cmbIdiomaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbIdiomaActionPerformed
        txtIdioma.setText(cmbIdioma.getSelectedItem().toString());
    }//GEN-LAST:event_cmbIdiomaActionPerformed

    private void cmbDisponivelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbDisponivelActionPerformed
        txtDisponivel.setText(cmbDisponivel.getSelectedItem().toString());
    }//GEN-LAST:event_cmbDisponivelActionPerformed

    private void txtTipos_IdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTipos_IdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTipos_IdActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bntAlterar;
    private javax.swing.JButton bntExcluir;
    private javax.swing.JButton btnFechar;
    public javax.swing.JButton btnSalvar;
    private javax.swing.JComboBox<String> cmbClassificacao;
    private javax.swing.JComboBox<String> cmbDisponivel;
    private javax.swing.JComboBox<String> cmbEditora;
    private javax.swing.JComboBox<String> cmbIdioma;
    private javax.swing.JComboBox<String> cmbTipo;
    private java.util.List<br.com.papyrus.view.Editoras> editorasList;
    private javax.persistence.Query editorasQuery;
    private javax.persistence.EntityManager entityManager;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPaneAcervo;
    private javax.swing.JLabel lblAno;
    private javax.swing.JLabel lblCDD;
    private javax.swing.JLabel lblCDU;
    private javax.swing.JLabel lblCUTTER;
    private javax.swing.JLabel lblClassificacao;
    private javax.swing.JLabel lblEdicao;
    private javax.swing.JLabel lblEditora;
    private javax.swing.JLabel lblExemplar;
    private javax.swing.JLabel lblISBN;
    private javax.swing.JLabel lblId;
    private javax.swing.JLabel lblIdioma;
    private javax.swing.JLabel lblObservacoes;
    private javax.swing.JLabel lblPaginas;
    private javax.swing.JLabel lblSerie;
    private javax.swing.JLabel lblSubTitulo;
    private javax.swing.JLabel lblTipo;
    private javax.swing.JLabel lblTitulo;
    private javax.swing.JLabel lblTombo;
    private javax.swing.JLabel lblVolume;
    private javax.swing.JTable tbACervo;
    private javax.swing.JTextField txtAno;
    private javax.swing.JFormattedTextField txtAquisicao;
    private javax.swing.JTextField txtCDD;
    private javax.swing.JTextField txtCDU;
    private javax.swing.JTextField txtCUTTER;
    public javax.swing.JTextField txtClassificacao_Id;
    private javax.swing.JTextField txtDisponivel;
    private javax.swing.JTextField txtEdicao;
    public javax.swing.JTextField txtEditoras_Id;
    private javax.swing.JTextField txtExemplar;
    private javax.swing.JTextField txtISBN;
    private javax.swing.JTextField txtId;
    private javax.swing.JTextField txtIdioma;
    private javax.swing.JTextField txtLocal;
    private javax.swing.JTextField txtObservacoes;
    private javax.swing.JTextField txtPaginas;
    private javax.swing.JTextField txtSerie;
    private javax.swing.JTextField txtSubTitulo;
    public javax.swing.JTextField txtTipos_Id;
    private javax.swing.JTextField txtTitulo;
    private javax.swing.JTextField txtTombo;
    private javax.swing.JTextField txtVolume;
    // End of variables declaration//GEN-END:variables

    ////////////////////////////////  ATENÇÃO  ////////////////////////////////
    //GET para os campo e botões do formulário para uso do ControllerAcervo
    ////////////////////////////////  ATENÇÃO  ////////////////////////////////
    public JButton getBtnSalvar() {  //Método criado na mão para ser usando por 
        return btnSalvar;
    }

    public JButton getBtnExcluir() {  //Método criado na mão para ser usando por ControllerAcervo
        return bntExcluir;
    }

    public JButton getBtnAlterar() {  //Método criado na mão para ser usando por ControllerAcervo
        return bntAlterar;
    }

    public JTextField getTxtId() { //Método criado na mão para ser usando por ControllerAcervo
        return txtId;
    }

    public JTextField getTxtTitulo() {
        return txtTitulo;
    }

    public JTextField getTxtSubTitulo() {
        return txtSubTitulo;
    }

    public JTextField getTxtSerie() {
        return txtSerie;
    }

    public JTextField getTxtIdioma() {
        return txtIdioma;
    }

    public JTextField getTxtExemplar() {
        return txtExemplar;
    }

    public JTextField getTxtEdicao() {
        return txtEdicao;
    }

    public JTextField getTxtPaginas() {
        return txtPaginas;
    }

    public JTextField getTxtVolume() {
        return txtVolume;
    }

    public JTextField getTxtAno() {
        return txtAno;
    }

    public JFormattedTextField getTxtAquisicao() {
        return txtAquisicao;
    }

    public JTextField getTxtLocal() {
        return txtLocal;
    }

    public JTextField getTxtEditoras_Id() {
        return txtEditoras_Id;
    }

    public JTextField getTxtClassificacao_Id() {
        return txtClassificacao_Id;
    }

    public JTextField getTxtTipos_Id() {
        return txtTipos_Id;
    }

    public JTextField getTxtTombo() {
        return txtTombo;
    }

    public JTextField getTxtCDU() {
        return txtCDU;
    }

    public JTextField getTxtCDD() {
        return txtCDD;
    }

    public JTextField getTxtCUTTER() {
        return txtCUTTER;
    }

    public JTextField getTxtISBN() {
        return txtISBN;
    }

    public JTextField getTxtObservacoes() {
        return txtObservacoes;
    }

    public JTextField getTxtDisponivel() {
        return txtDisponivel;
    }

    public JTable getTbAcervo() {
        return tbACervo;
    }

    /**
     * Método que linka o AbstractTableModel a tabela no formulário setTbAutores
     *
     * @param modelo vindo de ControllerAutores.carregar() com a lista do
     * TableModel
     */
    public void setTbAcervo(AbstractTableModel modelo) {
        this.tbACervo.setModel(modelo);
        this.tbACervo.setAutoResizeMode(JTable.AUTO_RESIZE_OFF);
        this.tbACervo.setSelectionBackground(Color.cyan);  //Põe cor azul na linha atual
        this.tbACervo.setSelectionForeground(Color.red);   //Põe letras em vermelho
        this.tbACervo.setBackground(Color.lightGray);      //põe cor de fundo azul
        this.tbACervo.getColumnModel().getColumn(0).setPreferredWidth(50); //Largura da coluna
        this.tbACervo.getColumnModel().getColumn(0).setResizable(true);    //Coluna redimenciosavel
        this.tbACervo.getColumnModel().getColumn(1).setPreferredWidth(250);
        this.tbACervo.getColumnModel().getColumn(1).setResizable(true);
        this.tbACervo.getColumnModel().getColumn(2).setPreferredWidth(150);
        this.tbACervo.getColumnModel().getColumn(2).setResizable(true);
        this.tbACervo.getColumnModel().getColumn(3).setPreferredWidth(100);
        this.tbACervo.getColumnModel().getColumn(3).setResizable(true);
    }
}
