package br.com.papyrus.view;

import java.awt.Color;
import javax.swing.JButton;
import javax.swing.JFormattedTextField;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.JTextField;
import javax.swing.table.AbstractTableModel;

/**
 * Classe que cria e gerencia a tela para Autores.
 *
 * @author Alexandre Luiz dos Santos
 */
public class ViewAcervo extends javax.swing.JInternalFrame {

    /**
     * Creates new form ViewAutores
     */
    public ViewAcervo() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bntAlterar = new javax.swing.JButton();
        btnSalvar = new javax.swing.JButton();
        bntExcluir = new javax.swing.JButton();
        btnFechar = new javax.swing.JButton();
        lblObservacoes = new javax.swing.JLabel();
        cmbDisponivel = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        txtId = new javax.swing.JTextField();
        txtTitulo = new javax.swing.JTextField();
        txtSubTitulo = new javax.swing.JTextField();
        txtSerie = new javax.swing.JTextField();
        cmbIdioma = new javax.swing.JComboBox<>();
        txtExemplar = new javax.swing.JTextField();
        txtEdicao = new javax.swing.JTextField();
        jScrollPaneAcervo = new javax.swing.JScrollPane();
        tbAcervo = new javax.swing.JTable();
        txtPaginas = new javax.swing.JTextField();
        txtVolume = new javax.swing.JTextField();
        txtAno = new javax.swing.JTextField();
        txtAquisicao = new javax.swing.JFormattedTextField();
        txtLocal = new javax.swing.JTextField();
        txtTombo = new javax.swing.JTextField();
        txtCDU = new javax.swing.JTextField();
        txtCDD = new javax.swing.JTextField();
        txtCUTTER = new javax.swing.JTextField();
        txtISBN = new javax.swing.JTextField();
        lblId = new javax.swing.JLabel();
        lblTitulo = new javax.swing.JLabel();
        lblSubTitulo = new javax.swing.JLabel();
        lblSerie = new javax.swing.JLabel();
        lblExemplar = new javax.swing.JLabel();
        lblEdicao = new javax.swing.JLabel();
        lblPaginas = new javax.swing.JLabel();
        lblVolume = new javax.swing.JLabel();
        txtObservacoes = new javax.swing.JTextField();
        lblAno = new javax.swing.JLabel();
        txtEditoras_Id = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        txtClassificacao_Id = new javax.swing.JTextField();
        txtTipos_Id = new javax.swing.JTextField();
        txtIdioma = new javax.swing.JTextField();
        txtDisponivel = new javax.swing.JTextField();
        txtNomeEditora = new javax.swing.JTextField();
        txtNomeClassificacao = new javax.swing.JTextField();
        txtNomeTipo = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        lblIdioma = new javax.swing.JLabel();
        lblEditora = new javax.swing.JLabel();
        lblClassificacao = new javax.swing.JLabel();
        lblTipo = new javax.swing.JLabel();
        lblTombo = new javax.swing.JLabel();
        lblCDU = new javax.swing.JLabel();
        lblCDD = new javax.swing.JLabel();
        lblCUTTER = new javax.swing.JLabel();
        lblISBN = new javax.swing.JLabel();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        setTitle("Autores");

        bntAlterar.setText("Alterar");
        bntAlterar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bntAlterarActionPerformed(evt);
            }
        });

        btnSalvar.setText("Salvar");
        btnSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalvarActionPerformed(evt);
            }
        });

        bntExcluir.setText("Excluir");
        bntExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bntExcluirActionPerformed(evt);
            }
        });

        btnFechar.setText("Fechar");
        btnFechar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFecharActionPerformed(evt);
            }
        });

        lblObservacoes.setText("Observações");

        cmbDisponivel.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Sim", "Não" }));
        cmbDisponivel.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(255, 0, 0), null));
        cmbDisponivel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbDisponivelActionPerformed(evt);
            }
        });

        jLabel3.setText("Disponivel");

        txtId.setEditable(false);

        txtTitulo.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(255, 0, 0), null));
        txtTitulo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTituloActionPerformed(evt);
            }
        });

        txtSerie.setToolTipText("Se pertence a uma serie, Exemplo: Harry potter.");

        cmbIdioma.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Alemão", "Árabe", "Bengali", "Chinês", "Coreano", "Espanhol", "Francês", "Hindi", "Inglês", "Italiano", "Japonês", "Javanês", "Marati", "Português", "Russo", "Tâmil", "Telugo", "Turco", "Urdu", "Vietnamita" }));
        cmbIdioma.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(255, 0, 0), null));
        cmbIdioma.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbIdiomaActionPerformed(evt);
            }
        });

        tbAcervo.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tbAcervo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbAcervoMouseClicked(evt);
            }
        });
        jScrollPaneAcervo.setViewportView(tbAcervo);

        txtAno.setToolTipText("Ano da edição da obra");

        txtAquisicao.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.DateFormatter(new java.text.SimpleDateFormat("yyyy/MM/dd"))));
        txtAquisicao.setToolTipText("Data de aquisição da obra");

        txtLocal.setToolTipText("Local onde o item está guardado.");

        txtTombo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTomboActionPerformed(evt);
            }
        });

        txtCDU.setToolTipText("Classificação Decimal Universal");

        txtCDD.setToolTipText("Classificação Decimal Dewey");

        txtCUTTER.setToolTipText("Indicam a autoria de uma obra literária.");

        lblId.setText("Código");

        lblTitulo.setText("Título");

        lblSubTitulo.setText("Subtítulo");

        lblSerie.setText("Série");

        lblExemplar.setText("Exemplar");

        lblEdicao.setText("Edição");

        lblPaginas.setText("Páginas");

        lblVolume.setText("Volume");

        txtObservacoes.setToolTipText("Observações a respeito da obra.");

        lblAno.setText("Ano");

        txtEditoras_Id.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(255, 0, 0), null));

        jLabel1.setText("Aquisição");

        txtClassificacao_Id.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(255, 0, 0), null));

        txtTipos_Id.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(255, 0, 0), null));
        txtTipos_Id.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTipos_IdActionPerformed(evt);
            }
        });

        txtIdioma.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtIdiomaActionPerformed(evt);
            }
        });

        txtNomeEditora.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNomeEditoraActionPerformed(evt);
            }
        });

        jLabel2.setText("Local");

        lblIdioma.setText("Idioma");

        lblEditora.setText("Editora");

        lblClassificacao.setText("Classificação");

        lblTipo.setText("Tipo");

        lblTombo.setText("Tombo");

        lblCDU.setText("CDU");

        lblCDD.setText("CDD");

        lblCUTTER.setText("CUTTER");

        lblISBN.setText("ISBN");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(lblId, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(10, 10, 10)
                        .addComponent(txtId, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(520, 520, 520)
                        .addComponent(lblExemplar)
                        .addGap(10, 10, 10)
                        .addComponent(txtExemplar, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(43, 43, 43)
                        .addComponent(lblEdicao)
                        .addGap(10, 10, 10)
                        .addComponent(txtEdicao, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(40, 40, 40)
                        .addComponent(lblPaginas, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(10, 10, 10)
                        .addComponent(txtPaginas, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(lblTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(10, 10, 10)
                        .addComponent(txtTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 511, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(58, 58, 58)
                        .addComponent(lblVolume, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtVolume, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(41, 41, 41)
                        .addComponent(lblAno, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(10, 10, 10)
                        .addComponent(txtAno, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(40, 40, 40)
                        .addComponent(jLabel1)
                        .addGap(10, 10, 10)
                        .addComponent(txtAquisicao, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(lblSerie, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(10, 10, 10)
                        .addComponent(txtSerie, javax.swing.GroupLayout.PREFERRED_SIZE, 313, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(28, 28, 28)
                        .addComponent(lblIdioma, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(10, 10, 10)
                        .addComponent(cmbIdioma, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(lblSubTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(12, 12, 12)
                        .addComponent(txtSubTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 509, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(58, 58, 58)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtLocal, javax.swing.GroupLayout.PREFERRED_SIZE, 468, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(btnSalvar)
                        .addGap(18, 18, 18)
                        .addComponent(bntAlterar)
                        .addGap(20, 20, 20)
                        .addComponent(bntExcluir)
                        .addGap(18, 18, 18)
                        .addComponent(btnFechar))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblTipo)
                                .addGap(51, 51, 51)
                                .addComponent(txtTipos_Id, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(6, 6, 6)
                                .addComponent(txtNomeTipo, javax.swing.GroupLayout.PREFERRED_SIZE, 432, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(711, 711, 711)
                                .addComponent(txtIdioma, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(6, 6, 6)
                                .addComponent(txtDisponivel, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblEditora)
                                .addGap(37, 37, 37)
                                .addComponent(txtEditoras_Id, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(6, 6, 6)
                                .addComponent(txtNomeEditora, javax.swing.GroupLayout.PREFERRED_SIZE, 432, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(58, 58, 58)
                                .addComponent(lblCDU, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(10, 10, 10)
                                .addComponent(txtTombo, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(49, 49, 49)
                                .addComponent(lblTombo, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(10, 10, 10)
                                .addComponent(txtCDU, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(24, 24, 24)
                                .addComponent(lblCDD, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtCDD, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(lblClassificacao)
                                        .addGap(10, 10, 10)
                                        .addComponent(txtClassificacao_Id, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(6, 6, 6)
                                        .addComponent(txtNomeClassificacao, javax.swing.GroupLayout.PREFERRED_SIZE, 432, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(lblObservacoes)
                                        .addGap(4, 4, 4)
                                        .addComponent(txtObservacoes, javax.swing.GroupLayout.PREFERRED_SIZE, 502, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(58, 58, 58)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(20, 20, 20)
                                        .addComponent(cmbDisponivel, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(lblISBN, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(10, 10, 10)
                                        .addComponent(txtCUTTER, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(49, 49, 49)
                                        .addComponent(lblCUTTER)
                                        .addGap(12, 12, 12)
                                        .addComponent(txtISBN, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addComponent(jScrollPaneAcervo, javax.swing.GroupLayout.PREFERRED_SIZE, 1170, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(23, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtExemplar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtEdicao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtPaginas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblId)
                            .addComponent(lblExemplar)
                            .addComponent(lblEdicao)
                            .addComponent(lblPaginas))))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(11, 11, 11)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(3, 3, 3)
                                .addComponent(lblTitulo))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(1, 1, 1)
                                .addComponent(txtTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(txtVolume, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(3, 3, 3)
                                .addComponent(lblAno))
                            .addComponent(txtAno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(3, 3, 3)
                                .addComponent(jLabel1))
                            .addComponent(txtAquisicao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addComponent(lblVolume)))
                .addGap(11, 11, 11)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtSubTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtLocal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblSubTitulo)
                            .addComponent(jLabel2))))
                .addGap(11, 11, 11)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblSerie)
                            .addComponent(txtSerie, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(4, 4, 4)
                        .addComponent(lblIdioma))
                    .addComponent(cmbIdioma, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 196, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(2, 2, 2)
                        .addComponent(lblEditora))
                    .addComponent(txtEditoras_Id, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtNomeEditora, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(lblCDU))
                    .addComponent(txtTombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblTombo, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtCDU, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblCDD)
                            .addComponent(txtCDD, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(6, 6, 6)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(4, 4, 4)
                        .addComponent(lblClassificacao))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addComponent(txtClassificacao_Id, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(txtNomeClassificacao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(lblISBN))
                    .addComponent(txtCUTTER, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(lblCUTTER))
                    .addComponent(txtISBN, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(6, 6, 6)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(lblTipo))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addComponent(txtTipos_Id, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(txtNomeTipo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(5, 5, 5)
                        .addComponent(lblObservacoes))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(2, 2, 2)
                        .addComponent(txtObservacoes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(cmbDisponivel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(6, 6, 6)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtIdioma, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtDisponivel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(31, 31, 31)
                .addComponent(jScrollPaneAcervo, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnSalvar)
                    .addComponent(bntAlterar)
                    .addComponent(bntExcluir)
                    .addComponent(btnFechar))
                .addGap(59, 59, 59))
        );

        getAccessibleContext().setAccessibleName("Acervo");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bntAlterarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bntAlterarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bntAlterarActionPerformed

    private void btnSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalvarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnSalvarActionPerformed

    private void btnFecharActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFecharActionPerformed
        // Exibe janela perguntando se deseja sair da tela autores
        int sair = JOptionPane.showConfirmDialog(null, "Tem certeza que deseja fechar o formulário ?", "Aviso", JOptionPane.YES_NO_OPTION);
        if (sair == JOptionPane.YES_OPTION) {
            this.dispose();
        }
    }//GEN-LAST:event_btnFecharActionPerformed

    private void bntExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bntExcluirActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bntExcluirActionPerformed

    private void cmbDisponivelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbDisponivelActionPerformed
        txtDisponivel.setText(cmbDisponivel.getSelectedItem().toString());
    }//GEN-LAST:event_cmbDisponivelActionPerformed

    private void txtTituloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTituloActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTituloActionPerformed

    private void cmbIdiomaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbIdiomaActionPerformed
        txtIdioma.setText(cmbIdioma.getSelectedItem().toString());
    }//GEN-LAST:event_cmbIdiomaActionPerformed

    private void tbAcervoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbAcervoMouseClicked

    }//GEN-LAST:event_tbAcervoMouseClicked

    private void txtTomboActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTomboActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTomboActionPerformed

    private void txtTipos_IdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTipos_IdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTipos_IdActionPerformed

    private void txtIdiomaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtIdiomaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtIdiomaActionPerformed

    private void txtNomeEditoraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNomeEditoraActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNomeEditoraActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bntAlterar;
    private javax.swing.JButton bntExcluir;
    private javax.swing.JButton btnFechar;
    public javax.swing.JButton btnSalvar;
    private javax.swing.JComboBox<String> cmbDisponivel;
    private javax.swing.JComboBox<String> cmbIdioma;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPaneAcervo;
    private javax.swing.JLabel lblAno;
    private javax.swing.JLabel lblCDD;
    private javax.swing.JLabel lblCDU;
    private javax.swing.JLabel lblCUTTER;
    private javax.swing.JLabel lblClassificacao;
    private javax.swing.JLabel lblEdicao;
    private javax.swing.JLabel lblEditora;
    private javax.swing.JLabel lblExemplar;
    private javax.swing.JLabel lblISBN;
    private javax.swing.JLabel lblId;
    private javax.swing.JLabel lblIdioma;
    private javax.swing.JLabel lblObservacoes;
    private javax.swing.JLabel lblPaginas;
    private javax.swing.JLabel lblSerie;
    private javax.swing.JLabel lblSubTitulo;
    private javax.swing.JLabel lblTipo;
    private javax.swing.JLabel lblTitulo;
    private javax.swing.JLabel lblTombo;
    private javax.swing.JLabel lblVolume;
    private javax.swing.JTable tbAcervo;
    private javax.swing.JTextField txtAno;
    private javax.swing.JFormattedTextField txtAquisicao;
    private javax.swing.JTextField txtCDD;
    private javax.swing.JTextField txtCDU;
    private javax.swing.JTextField txtCUTTER;
    public javax.swing.JTextField txtClassificacao_Id;
    private javax.swing.JTextField txtDisponivel;
    private javax.swing.JTextField txtEdicao;
    public javax.swing.JTextField txtEditoras_Id;
    private javax.swing.JTextField txtExemplar;
    private javax.swing.JTextField txtISBN;
    private javax.swing.JTextField txtId;
    private javax.swing.JTextField txtIdioma;
    private javax.swing.JTextField txtLocal;
    private javax.swing.JTextField txtNomeClassificacao;
    public static javax.swing.JTextField txtNomeEditora;
    private javax.swing.JTextField txtNomeTipo;
    private javax.swing.JTextField txtObservacoes;
    private javax.swing.JTextField txtPaginas;
    private javax.swing.JTextField txtSerie;
    private javax.swing.JTextField txtSubTitulo;
    public javax.swing.JTextField txtTipos_Id;
    private javax.swing.JTextField txtTitulo;
    private javax.swing.JTextField txtTombo;
    private javax.swing.JTextField txtVolume;
    // End of variables declaration//GEN-END:variables

    //GET para os campos e botões do formulário para uso do ControllerAutores
    public JButton getBtnSalvar() {
        return btnSalvar;
    }

    public JButton getBtnExcluir() {
        return bntExcluir;
    }

    public JButton getBtnAlterar() {
        return bntAlterar;
    }

    public JTextField getTxtId() {
        return txtId;
    }

    public JTextField getTxtTitulo() {
        return txtTitulo;
    }

    public JTextField getTxtSubTitulo() {
        return txtSubTitulo;
    }

    public JTextField getTxtSerie() {
        return txtSerie;
    }

    public JTextField getTxtIdioma() {
        return txtIdioma;
    }

    public JTextField getTxtExemplar() {
        return txtExemplar;
    }

    public JTextField getTxtEdicao() {
        return txtEdicao;
    }

    public JTextField getTxtPaginas() {
        return txtPaginas;
    }

    public JTextField getTxtVolume() {
        return txtVolume;
    }

    public JTextField getTxtAno() {
        return txtAno;
    }

    public JFormattedTextField getTxtAquisicao() {
        return txtAquisicao;
    }

    public JTextField getTxtLocal() {
        return txtLocal;
    }

    public JTextField getTxtEditoras_Id() {
        return txtEditoras_Id;
    }

    public JTextField getTxtClassificacao_Id() {
        return txtClassificacao_Id;
    }

    public JTextField getTxtTipos_Id() {
        return txtTipos_Id;
    }

    public JTextField getTxtTombo() {
        return txtTombo;
    }

    public JTextField getTxtCDU() {
        return txtCDU;
    }

    public JTextField getTxtCDD() {
        return txtCDD;
    }

    public JTextField getTxtCUTTER() {
        return txtCUTTER;
    }

    public JTextField getTxtISBN() {
        return txtISBN;
    }

    public JTextField getTxtObservacoes() {
        return txtObservacoes;
    }

    public JTextField getTxtDisponivel() {
        return txtDisponivel;
    }

    public JTable getTbAcervo() {
        return tbAcervo;
    }

    public JTextField getTxtNomeEditora() {
        return txtNomeEditora;
    }

    public JTextField getTxtNomeClassificacao() {
        return txtNomeClassificacao;
    }

    public JTextField getTxtNomeTipo() {
        return txtNomeTipo;

    }

    /**
     * Método que linka o AbstractTableModel a tabela no formulário setTbAutores
     *
     * @param modelo vindo de ControllerAutores.carregar() com a lista do
     * TableModel
     */
    public void setTbAcervo(AbstractTableModel modelo) {
        this.tbAcervo.setModel(modelo);
        this.tbAcervo.setAutoResizeMode(JTable.AUTO_RESIZE_OFF);
        this.tbAcervo.setSelectionBackground(Color.cyan);  //Põe cor azul na linha atual
        this.tbAcervo.setSelectionForeground(Color.red);   //Põe letras em vermelho
        this.tbAcervo.setBackground(Color.lightGray);      //põe cor de fundo azul
        this.tbAcervo.getColumnModel().getColumn(0).setPreferredWidth(50); //Largura da coluna
        this.tbAcervo.getColumnModel().getColumn(0).setResizable(true);    //Coluna redimenciosavel
        this.tbAcervo.getColumnModel().getColumn(1).setPreferredWidth(250);
        this.tbAcervo.getColumnModel().getColumn(1).setResizable(true);
        this.tbAcervo.getColumnModel().getColumn(2).setPreferredWidth(150);
        this.tbAcervo.getColumnModel().getColumn(2).setResizable(true);
        this.tbAcervo.getColumnModel().getColumn(3).setPreferredWidth(100);
        this.tbAcervo.getColumnModel().getColumn(3).setResizable(true);
    }
}
