package br.com.papyrus.view;

import br.com.papyrus.controller.ControllerAcervoComboBoxAutores;
import br.com.papyrus.controller.ControllerAcervoComboBoxClassificacoes;
import br.com.papyrus.controller.ControllerAcervoComboBoxEditoras;
import br.com.papyrus.controller.ControllerAcervoComboBoxIdioma;
import br.com.papyrus.controller.ControllerAcervoComboBoxTipos;
import br.com.papyrus.controller.StringLimitada;
import java.awt.Color;
import javax.swing.JButton;
import javax.swing.JFormattedTextField;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.JTextField;
import javax.swing.table.AbstractTableModel;

/**
 * Classe que cria e gerencia a tela para Acervo.
 *
 * @author Alexandre Luiz dos Santos
 */
public class ViewAcervo extends javax.swing.JInternalFrame {

    //Instanciando a classe que abre a janela com o comboBox
    //Será verificado se a janela está aberta, caso esteja não permite abrir novamente.
    ControllerAcervoComboBoxIdioma idioma;
    ControllerAcervoComboBoxEditoras editoras;
    ControllerAcervoComboBoxClassificacoes classificacoes;
    ControllerAcervoComboBoxTipos tipos;
    ControllerAcervoComboBoxAutores autores;

    public ViewAcervo() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bntAlterar = new javax.swing.JButton();
        btnSalvar = new javax.swing.JButton();
        bntExcluir = new javax.swing.JButton();
        btnFechar = new javax.swing.JButton();
        lblObservacoes = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jScrollPaneAcervo = new javax.swing.JScrollPane();
        tbAcervo = new javax.swing.JTable();
        txtCDU = new javax.swing.JTextField();
        txtTombo = new javax.swing.JTextField();
        txtCDD = new javax.swing.JTextField();
        txtISBN = new javax.swing.JTextField();
        txtCUTTER = new javax.swing.JTextField();
        txtObservacoes = new javax.swing.JTextField();
        txtEditoras_Id = new javax.swing.JTextField();
        txtClassificacao_Id = new javax.swing.JTextField();
        txtTipos_Id = new javax.swing.JTextField();
        txtIdioma = new javax.swing.JTextField();
        txtDisponivel = new javax.swing.JTextField();
        txtNomeEditora = new javax.swing.JTextField();
        txtNomeClassificacao = new javax.swing.JTextField();
        txtNomeTipo = new javax.swing.JTextField();
        lblEditora = new javax.swing.JLabel();
        lblClassificacao = new javax.swing.JLabel();
        lblTipo = new javax.swing.JLabel();
        lblTombo = new javax.swing.JLabel();
        lblCDU = new javax.swing.JLabel();
        lblCDD = new javax.swing.JLabel();
        lblCUTTER = new javax.swing.JLabel();
        lblISBN = new javax.swing.JLabel();
        lblId = new javax.swing.JLabel();
        txtId = new javax.swing.JTextField();
        lblTitulo = new javax.swing.JLabel();
        txtTitulo = new javax.swing.JTextField();
        txtSubTitulo = new javax.swing.JTextField();
        lblSubTitulo = new javax.swing.JLabel();
        lblSerie = new javax.swing.JLabel();
        txtSerie = new javax.swing.JTextField();
        lblIdioma = new javax.swing.JLabel();
        txtExemplar = new javax.swing.JTextField();
        lblExemplar = new javax.swing.JLabel();
        lblVolume = new javax.swing.JLabel();
        txtVolume = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txtLocal = new javax.swing.JTextField();
        txtAno = new javax.swing.JTextField();
        lblAno = new javax.swing.JLabel();
        txtEdicao = new javax.swing.JTextField();
        lblEdicao = new javax.swing.JLabel();
        lblPaginas = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        txtAquisicao = new javax.swing.JFormattedTextField();
        txtPaginas = new javax.swing.JTextField();
        btnDuplicar = new javax.swing.JButton();
        lblAutor = new javax.swing.JLabel();
        txtAutoresNome = new javax.swing.JTextField();
        txtAutores_Id = new javax.swing.JTextField();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        setTitle("ACERVO");
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        bntAlterar.setText("Alterar");
        getContentPane().add(bntAlterar, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 480, -1, -1));

        btnSalvar.setText("Salvar");
        getContentPane().add(btnSalvar, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 480, -1, -1));

        bntExcluir.setText("Excluir");
        getContentPane().add(bntExcluir, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 480, -1, -1));

        btnFechar.setText("Fechar");
        btnFechar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFecharActionPerformed(evt);
            }
        });
        getContentPane().add(btnFechar, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 480, -1, -1));

        lblObservacoes.setText("Observações");
        lblObservacoes.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        getContentPane().add(lblObservacoes, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 250, 80, 20));

        jLabel3.setText("Disponivel");
        jLabel3.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 220, 60, 20));

        tbAcervo.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPaneAcervo.setViewportView(tbAcervo);

        getContentPane().add(jScrollPaneAcervo, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 310, 1150, 158));

        txtCDU.setDocument(new StringLimitada(20));
        getContentPane().add(txtCDU, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 160, 105, -1));

        txtTombo.setToolTipText("Classificação Decimal Universal");
        getContentPane().add(txtTombo, new org.netbeans.lib.awtextra.AbsoluteConstraints(870, 190, 105, -1));

        txtCDD.setDocument(new StringLimitada(20));
        txtCDD.setToolTipText("Classificação Decimal Dewey");
        getContentPane().add(txtCDD, new org.netbeans.lib.awtextra.AbsoluteConstraints(870, 160, 105, -1));

        txtISBN.setDocument(new StringLimitada(15));
        txtISBN.setToolTipText("Indicam a autoria de uma obra literária.");
        getContentPane().add(txtISBN, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 190, 105, -1));

        txtCUTTER.setDocument(new StringLimitada(10));
        getContentPane().add(txtCUTTER, new org.netbeans.lib.awtextra.AbsoluteConstraints(1060, 160, 105, -1));

        txtObservacoes.setDocument(new StringLimitada(100));
        txtObservacoes.setToolTipText("Observações a respeito da obra.");
        getContentPane().add(txtObservacoes, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 250, 470, -1));

        txtEditoras_Id.setEditable(false);
        txtEditoras_Id.setToolTipText("Campo obrigatório");
        txtEditoras_Id.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtEditoras_IdMouseClicked(evt);
            }
        });
        getContentPane().add(txtEditoras_Id, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 190, 60, -1));

        txtClassificacao_Id.setEditable(false);
        txtClassificacao_Id.setToolTipText("Campo obrigatório");
        txtClassificacao_Id.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtClassificacao_IdMouseClicked(evt);
            }
        });
        getContentPane().add(txtClassificacao_Id, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 220, 60, -1));

        txtTipos_Id.setEditable(false);
        txtTipos_Id.setToolTipText("Campo obrigatório");
        txtTipos_Id.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtTipos_IdMouseClicked(evt);
            }
        });
        getContentPane().add(txtTipos_Id, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 250, 60, -1));

        txtIdioma.setEditable(false);
        txtIdioma.setToolTipText("Campo obrigatório");
        txtIdioma.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtIdiomaMouseClicked(evt);
            }
        });
        getContentPane().add(txtIdioma, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 110, 130, -1));

        txtDisponivel.setDocument(new StringLimitada(3));
        txtDisponivel.setToolTipText("Campo obrigatório");
        getContentPane().add(txtDisponivel, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 220, 53, -1));

        txtNomeEditora.setEditable(false);
        getContentPane().add(txtNomeEditora, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 190, 420, -1));

        txtNomeClassificacao.setEditable(false);
        getContentPane().add(txtNomeClassificacao, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 220, 420, -1));

        txtNomeTipo.setEditable(false);
        getContentPane().add(txtNomeTipo, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 250, 420, -1));

        lblEditora.setText("Editora");
        lblEditora.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        getContentPane().add(lblEditora, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 190, 80, 20));

        lblClassificacao.setText("Classificação");
        lblClassificacao.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        getContentPane().add(lblClassificacao, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 220, 80, 20));

        lblTipo.setText("Tipo");
        lblTipo.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        getContentPane().add(lblTipo, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 250, 80, 20));

        lblTombo.setText("Tombo");
        lblTombo.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        getContentPane().add(lblTombo, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 190, 39, 20));

        lblCDU.setText("CDU");
        lblCDU.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        getContentPane().add(lblCDU, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 160, 40, 20));

        lblCDD.setText("CDD");
        lblCDD.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        getContentPane().add(lblCDD, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 160, 40, 20));

        lblCUTTER.setText("CUTTER");
        lblCUTTER.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        getContentPane().add(lblCUTTER, new org.netbeans.lib.awtextra.AbsoluteConstraints(1010, 160, -1, 20));

        lblISBN.setText("ISBN");
        lblISBN.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        getContentPane().add(lblISBN, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 190, 40, 20));

        lblId.setText("Código");
        lblId.setToolTipText("Código gerado automaticamente pelo sistema");
        lblId.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        getContentPane().add(lblId, new org.netbeans.lib.awtextra.AbsoluteConstraints(18, 20, 50, 20));

        txtId.setEditable(false);
        getContentPane().add(txtId, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 20, 49, -1));

        lblTitulo.setText("Título");
        lblTitulo.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        getContentPane().add(lblTitulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(18, 51, 50, 20));

        txtTitulo.setDocument(new StringLimitada(45));
        txtTitulo.setToolTipText("Campo obrigatório");
        getContentPane().add(txtTitulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 50, 511, -1));

        txtSubTitulo.setDocument(new StringLimitada(45));
        getContentPane().add(txtSubTitulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 80, 509, -1));

        lblSubTitulo.setText("Subtítulo");
        lblSubTitulo.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        getContentPane().add(lblSubTitulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 80, 50, 20));

        lblSerie.setText("Série");
        lblSerie.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        getContentPane().add(lblSerie, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 110, 50, 20));

        txtSerie.setDocument(new StringLimitada(45));
        txtSerie.setToolTipText("Se pertence a uma serie, Exemplo: Harry potter.");
        getContentPane().add(txtSerie, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 110, 313, -1));

        lblIdioma.setText("Idioma");
        lblIdioma.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        getContentPane().add(lblIdioma, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 110, 50, 20));

        txtExemplar.setDocument(new StringLimitada(2));
        getContentPane().add(txtExemplar, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 40, 90, -1));

        lblExemplar.setText("Exemplar");
        lblExemplar.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        getContentPane().add(lblExemplar, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 40, 60, 20));

        lblVolume.setText("Volume");
        lblVolume.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        getContentPane().add(lblVolume, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 70, 50, 20));

        txtVolume.setDocument(new StringLimitada(2));
        getContentPane().add(txtVolume, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 70, 90, -1));

        jLabel2.setText("Local");
        jLabel2.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 100, 50, 20));

        txtLocal.setDocument(new StringLimitada(45));
        txtLocal.setToolTipText("Local onde o item está guardado.");
        getContentPane().add(txtLocal, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 100, 470, -1));

        txtAno.setDocument(new StringLimitada(4));
        txtAno.setToolTipText("Ano da edição da obra");
        getContentPane().add(txtAno, new org.netbeans.lib.awtextra.AbsoluteConstraints(890, 70, 90, -1));

        lblAno.setText("Ano");
        lblAno.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        getContentPane().add(lblAno, new org.netbeans.lib.awtextra.AbsoluteConstraints(840, 70, 40, 20));

        txtEdicao.setDocument(new StringLimitada(10));
        getContentPane().add(txtEdicao, new org.netbeans.lib.awtextra.AbsoluteConstraints(890, 40, 90, -1));

        lblEdicao.setText("Edição");
        lblEdicao.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        getContentPane().add(lblEdicao, new org.netbeans.lib.awtextra.AbsoluteConstraints(840, 40, 40, 20));

        lblPaginas.setText("Páginas");
        lblPaginas.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        getContentPane().add(lblPaginas, new org.netbeans.lib.awtextra.AbsoluteConstraints(1020, 40, 50, 20));

        jLabel1.setText("Aquisição");
        jLabel1.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1020, 70, 60, 20));

        txtAquisicao.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.DateFormatter(new java.text.SimpleDateFormat("yyyy/MM/dd"))));
        txtAquisicao.setToolTipText("Data de aquisição da obra. Formato AAAA/MM/DD (Ano, Mês, Dia)");
        getContentPane().add(txtAquisicao, new org.netbeans.lib.awtextra.AbsoluteConstraints(1080, 70, 90, -1));

        txtPaginas.setDocument(new StringLimitada(4));
        getContentPane().add(txtPaginas, new org.netbeans.lib.awtextra.AbsoluteConstraints(1080, 40, 90, -1));

        btnDuplicar.setText("Duplicar");
        btnDuplicar.setToolTipText("Duplica o registro selecionado.");
        getContentPane().add(btnDuplicar, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 480, -1, -1));

        lblAutor.setText("Autor");
        lblAutor.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        getContentPane().add(lblAutor, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 140, 50, 20));
        getContentPane().add(txtAutoresNome, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 140, 440, -1));

        txtAutores_Id.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtAutores_IdMouseClicked(evt);
            }
        });
        getContentPane().add(txtAutores_Id, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 140, 60, -1));

        setBounds(0, 0, 1232, 553);
    }// </editor-fold>//GEN-END:initComponents

    private void btnFecharActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFecharActionPerformed
        // Exibe janela perguntando se deseja sair da tela autores
        int sair = JOptionPane.showConfirmDialog(null, "Tem certeza que deseja fechar o formulário ?", "Aviso", JOptionPane.YES_NO_OPTION);
        if (sair == JOptionPane.YES_OPTION) {
            this.dispose();
        }
    }//GEN-LAST:event_btnFecharActionPerformed

    private void txtIdiomaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtIdiomaMouseClicked
        if (idioma == null) {
            idioma = new ControllerAcervoComboBoxIdioma();
            idioma.setVisible(true);
        } else {
            idioma.setVisible(true);
            idioma.setState(JFrame.NORMAL);
        }
    }//GEN-LAST:event_txtIdiomaMouseClicked

    private void txtEditoras_IdMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtEditoras_IdMouseClicked
        if (editoras == null) {
            editoras = new ControllerAcervoComboBoxEditoras();
            editoras.setVisible(true);
        } else {
            editoras.setVisible(true);
            editoras.setState(JFrame.NORMAL);
        }
    }//GEN-LAST:event_txtEditoras_IdMouseClicked

    private void txtTipos_IdMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtTipos_IdMouseClicked
        if (tipos == null) {
            tipos = new ControllerAcervoComboBoxTipos();
            tipos.setVisible(true);
        } else {
            tipos.setVisible(true);
            tipos.setState(JFrame.NORMAL);
        }
    }//GEN-LAST:event_txtTipos_IdMouseClicked

    private void txtClassificacao_IdMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtClassificacao_IdMouseClicked
        if (classificacoes == null) {
            classificacoes = new ControllerAcervoComboBoxClassificacoes();
            classificacoes.setVisible(true);
        } else {
            classificacoes.setVisible(true);
            classificacoes.setState(JFrame.NORMAL);
        }
    }//GEN-LAST:event_txtClassificacao_IdMouseClicked

    private void txtAutores_IdMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtAutores_IdMouseClicked
        if (autores == null) {
            autores = new ControllerAcervoComboBoxAutores();
            autores.setVisible(true);
        } else {
            autores.setVisible(true);
            autores.setState(JFrame.NORMAL);
        }
    }//GEN-LAST:event_txtAutores_IdMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bntAlterar;
    private javax.swing.JButton bntExcluir;
    public static javax.swing.JButton btnDuplicar;
    private javax.swing.JButton btnFechar;
    public javax.swing.JButton btnSalvar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPaneAcervo;
    private javax.swing.JLabel lblAno;
    private javax.swing.JLabel lblAutor;
    private javax.swing.JLabel lblCDD;
    private javax.swing.JLabel lblCDU;
    private javax.swing.JLabel lblCUTTER;
    private javax.swing.JLabel lblClassificacao;
    private javax.swing.JLabel lblEdicao;
    private javax.swing.JLabel lblEditora;
    private javax.swing.JLabel lblExemplar;
    private javax.swing.JLabel lblISBN;
    private javax.swing.JLabel lblId;
    private javax.swing.JLabel lblIdioma;
    private javax.swing.JLabel lblObservacoes;
    private javax.swing.JLabel lblPaginas;
    private javax.swing.JLabel lblSerie;
    private javax.swing.JLabel lblSubTitulo;
    private javax.swing.JLabel lblTipo;
    private javax.swing.JLabel lblTitulo;
    private javax.swing.JLabel lblTombo;
    private javax.swing.JLabel lblVolume;
    private javax.swing.JTable tbAcervo;
    private javax.swing.JTextField txtAno;
    private javax.swing.JFormattedTextField txtAquisicao;
    public static javax.swing.JTextField txtAutoresNome;
    public static javax.swing.JTextField txtAutores_Id;
    private javax.swing.JTextField txtCDD;
    private javax.swing.JTextField txtCDU;
    private javax.swing.JTextField txtCUTTER;
    public static javax.swing.JTextField txtClassificacao_Id;
    private javax.swing.JTextField txtDisponivel;
    private javax.swing.JTextField txtEdicao;
    public static javax.swing.JTextField txtEditoras_Id;
    private javax.swing.JTextField txtExemplar;
    private javax.swing.JTextField txtISBN;
    private javax.swing.JTextField txtId;
    public static javax.swing.JTextField txtIdioma;
    private javax.swing.JTextField txtLocal;
    public static javax.swing.JTextField txtNomeClassificacao;
    public static javax.swing.JTextField txtNomeEditora;
    public static javax.swing.JTextField txtNomeTipo;
    private javax.swing.JTextField txtObservacoes;
    private javax.swing.JTextField txtPaginas;
    private javax.swing.JTextField txtSerie;
    private javax.swing.JTextField txtSubTitulo;
    public static javax.swing.JTextField txtTipos_Id;
    private javax.swing.JTextField txtTitulo;
    private javax.swing.JTextField txtTombo;
    private javax.swing.JTextField txtVolume;
    // End of variables declaration//GEN-END:variables

    //GET para os campos e botões do formulário para uso do ControllerAutores
    public JButton getBtnDuplicar() {
        return btnDuplicar;
    }

    public JButton getBtnSalvar() {
        return btnSalvar;
    }

    public JButton getBtnExcluir() {
        return bntExcluir;
    }

    public JButton getBtnAlterar() {
        return bntAlterar;
    }

    public JTextField getTxtId() {
        return txtId;
    }

    public JTextField getTxtTitulo() {
        return txtTitulo;
    }

    public JTextField getTxtSubTitulo() {
        return txtSubTitulo;
    }

    public JTextField getTxtSerie() {
        return txtSerie;
    }

    public JTextField getTxtIdioma() {
        return txtIdioma;
    }

    public JTextField getTxtExemplar() {
        return txtExemplar;
    }

    public JTextField getTxtEdicao() {
        return txtEdicao;
    }

    public JTextField getTxtPaginas() {
        return txtPaginas;
    }

    public JTextField getTxtVolume() {
        return txtVolume;
    }

    public JTextField getTxtAno() {
        return txtAno;
    }

    public JFormattedTextField getTxtAquisicao() {
        return txtAquisicao;
    }

    public JTextField getTxtLocal() {
        return txtLocal;
    }

    public JTextField getTxtEditoras_Id() {
        return txtEditoras_Id;
    }

    public JTextField getTxtClassificacao_Id() {
        return txtClassificacao_Id;
    }

    public JTextField getTxtTipos_Id() {
        return txtTipos_Id;
    }

    public JTextField getTxtTombo() {
        return txtCDU;
    }

    public JTextField getTxtCDU() {
        return txtTombo;
    }

    public JTextField getTxtCDD() {
        return txtCDD;
    }

    public JTextField getTxtCUTTER() {
        return txtISBN;
    }

    public JTextField getTxtISBN() {
        return txtCUTTER;
    }

    public JTextField getTxtObservacoes() {
        return txtObservacoes;
    }

    public JTextField getTxtDisponivel() {
        return txtDisponivel;
    }

    public JTable getTbAcervo() {
        return tbAcervo;
    }

    public JTextField getTxtNomeEditora() {
        return txtNomeEditora;
    }

    public JTextField getTxtNomeClassificacao() {
        return txtNomeClassificacao;
    }

    public JTextField getTxtNomeTipo() {
        return txtNomeTipo;

    }

    public JTextField getTxtAutores_Id() {
        return txtAutores_Id;
    }

    public JTextField getTxtAutoresNome() {
        return txtAutoresNome;
    }

    /**
     * Método que linka o AbstractTableModel a tabela no formulário setTbAutores
     *
     * @param modelo vindo de ControllerAutores.carregar() com a lista do
     * TableModel
     */
    public void setTbAcervo(AbstractTableModel modelo) {
        this.tbAcervo.setModel(modelo);
        this.tbAcervo.setAutoResizeMode(JTable.AUTO_RESIZE_OFF);
        this.tbAcervo.setSelectionBackground(Color.cyan);  //Põe cor azul na linha atual
        this.tbAcervo.setSelectionForeground(Color.red);   //Põe letras em vermelho
        this.tbAcervo.setBackground(Color.lightGray);      //põe cor de fundo azul
        this.tbAcervo.getColumnModel().getColumn(0).setPreferredWidth(50); //Largura da coluna
        this.tbAcervo.getColumnModel().getColumn(0).setResizable(true);    //Coluna redimenciosavel
        this.tbAcervo.getColumnModel().getColumn(1).setPreferredWidth(200);
        this.tbAcervo.getColumnModel().getColumn(1).setResizable(true);
        this.tbAcervo.getColumnModel().getColumn(2).setPreferredWidth(150);
        this.tbAcervo.getColumnModel().getColumn(2).setResizable(true);
        this.tbAcervo.getColumnModel().getColumn(3).setPreferredWidth(150);
        this.tbAcervo.getColumnModel().getColumn(3).setResizable(true);
    }
}
