package br.com.papyrus.view;

import br.com.papyrus.controller.ControllerDevolucoesComboBoxAcervo;
import br.com.papyrus.controller.StringLimitada;
import br.com.papyrus.model.CriarConexao;
import java.awt.Color;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.JButton;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.JTextField;
import javax.swing.table.AbstractTableModel;

/**
 * Classe que cria e gerencia a tela para Devolucoes.
 *
 * @author Alexandre Luiz dos Santos
 */
public class ViewDevolucoes extends javax.swing.JInternalFrame {

    ControllerDevolucoesComboBoxAcervo acervo;

    public ViewDevolucoes() {
        initComponents();
        tituloViewDevolucoes();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblLeitor = new javax.swing.JLabel();
        txtLeitores_Id = new javax.swing.JTextField();
        lblAcervo = new javax.swing.JLabel();
        txtAcervo_Id = new javax.swing.JTextField();
        btnSalvar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbEmprestimos = new javax.swing.JTable();
        btnFechar = new javax.swing.JButton();
        txtNomeLeitores = new javax.swing.JTextField();
        txtTituloAcervo = new javax.swing.JTextField();
        lblDevolucao = new javax.swing.JLabel();
        txtDevolucao = new javax.swing.JTextField();
        lblSubTituloAcervo = new javax.swing.JLabel();
        txtSubTituloAcervo = new javax.swing.JTextField();
        lblExemplarAcervo = new javax.swing.JLabel();
        txtExemplarAcervo = new javax.swing.JTextField();
        lblEdicaoAcervo = new javax.swing.JLabel();
        txtEdicaoAcervo = new javax.swing.JTextField();
        lblVolumeAcervo = new javax.swing.JLabel();
        txtVolumeAcervo = new javax.swing.JTextField();
        lblDisponivelAcervo = new javax.swing.JLabel();
        txtDisponivelAcervo = new javax.swing.JTextField();
        lblLocalAcervo = new javax.swing.JLabel();
        txtLocalAcervo = new javax.swing.JTextField();
        lblTitulo = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        txtAutorNome = new javax.swing.JTextField();
        txtAutores_Id = new javax.swing.JTextField();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        setTitle("DEVOLUÇÕES");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblLeitor.setText("Leitor");
        lblLeitor.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        getContentPane().add(lblLeitor, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 20, 40, 20));

        txtLeitores_Id.setEditable(false);
        getContentPane().add(txtLeitores_Id, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 20, 60, -1));

        lblAcervo.setText("Acervo");
        lblAcervo.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        getContentPane().add(lblAcervo, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 20, 40, 20));

        txtAcervo_Id.setDocument(new StringLimitada(45));
        txtAcervo_Id.setEditable(false);
        txtAcervo_Id.setToolTipText("Nome do autor da obra");
        txtAcervo_Id.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtAcervo_IdMouseClicked(evt);
            }
        });
        getContentPane().add(txtAcervo_Id, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 20, 60, -1));

        btnSalvar.setText("Salvar");
        getContentPane().add(btnSalvar, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 530, -1, -1));

        tbEmprestimos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tbEmprestimos);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(48, 244, 1100, 270));

        btnFechar.setText("Fechar");
        btnFechar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFecharActionPerformed(evt);
            }
        });
        getContentPane().add(btnFechar, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 530, -1, -1));

        txtNomeLeitores.setEditable(false);
        getContentPane().add(txtNomeLeitores, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 20, 350, -1));

        txtTituloAcervo.setEditable(false);
        getContentPane().add(txtTituloAcervo, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 20, 450, -1));

        lblDevolucao.setText("Devolução");
        lblDevolucao.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        getContentPane().add(lblDevolucao, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 60, 60, 20));

        txtDevolucao.setEditable(false);
        getContentPane().add(txtDevolucao, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 60, 110, -1));

        lblSubTituloAcervo.setText("SubTitulo");
        getContentPane().add(lblSubTituloAcervo, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 60, 60, 20));
        getContentPane().add(txtSubTituloAcervo, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 60, 500, -1));

        lblExemplarAcervo.setText("Exemplar");
        lblExemplarAcervo.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        getContentPane().add(lblExemplarAcervo, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 100, 60, 20));
        getContentPane().add(txtExemplarAcervo, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 100, 110, -1));

        lblEdicaoAcervo.setText("Edição");
        lblEdicaoAcervo.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        getContentPane().add(lblEdicaoAcervo, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 100, 50, 20));
        getContentPane().add(txtEdicaoAcervo, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 100, 120, -1));

        lblVolumeAcervo.setText("Volume");
        lblVolumeAcervo.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        getContentPane().add(lblVolumeAcervo, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 140, 50, 20));
        getContentPane().add(txtVolumeAcervo, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 140, 110, -1));

        lblDisponivelAcervo.setText("Disponivel");
        lblDisponivelAcervo.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        getContentPane().add(lblDisponivelAcervo, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 140, 60, 20));
        getContentPane().add(txtDisponivelAcervo, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 140, 120, -1));

        lblLocalAcervo.setText("Local");
        lblLocalAcervo.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        getContentPane().add(lblLocalAcervo, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 140, 40, 20));

        txtLocalAcervo.setToolTipText("Local onde o acervo está guardado fisicamente.");
        getContentPane().add(txtLocalAcervo, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 140, 520, -1));

        lblTitulo.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblTitulo.setText("ITENS DISPONÍVEIS PARA DEVOLUÇÃO");
        getContentPane().add(lblTitulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 210, 1100, 20));

        jLabel1.setText("Autor");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 100, 40, 20));
        getContentPane().add(txtAutorNome, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 100, 450, -1));
        getContentPane().add(txtAutores_Id, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 100, 60, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnFecharActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFecharActionPerformed
        int sair = JOptionPane.showConfirmDialog(null, "Tem certeza que deseja fechar o formulário ?", "Aviso", JOptionPane.YES_NO_OPTION);
        if (sair == JOptionPane.YES_OPTION) {
            this.dispose();
        }
    }//GEN-LAST:event_btnFecharActionPerformed

    private void txtAcervo_IdMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtAcervo_IdMouseClicked
        if (acervo == null) {
            acervo = new ControllerDevolucoesComboBoxAcervo();
            acervo.setVisible(true);
        } else {
            acervo.setVisible(true);
            acervo.setState(JFrame.NORMAL);
        }
    }//GEN-LAST:event_txtAcervo_IdMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnFechar;
    public javax.swing.JButton btnSalvar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblAcervo;
    private javax.swing.JLabel lblDevolucao;
    private javax.swing.JLabel lblDisponivelAcervo;
    private javax.swing.JLabel lblEdicaoAcervo;
    private javax.swing.JLabel lblExemplarAcervo;
    private javax.swing.JLabel lblLeitor;
    private javax.swing.JLabel lblLocalAcervo;
    private javax.swing.JLabel lblSubTituloAcervo;
    private javax.swing.JLabel lblTitulo;
    private javax.swing.JLabel lblVolumeAcervo;
    private javax.swing.JTable tbEmprestimos;
    public static javax.swing.JTextField txtAcervo_Id;
    public static javax.swing.JTextField txtAutorNome;
    public static javax.swing.JTextField txtAutores_Id;
    public static javax.swing.JTextField txtDevolucao;
    public static javax.swing.JTextField txtDisponivelAcervo;
    public static javax.swing.JTextField txtEdicaoAcervo;
    public static javax.swing.JTextField txtExemplarAcervo;
    public static javax.swing.JTextField txtLeitores_Id;
    public static javax.swing.JTextField txtLocalAcervo;
    public static javax.swing.JTextField txtNomeLeitores;
    public static javax.swing.JTextField txtSubTituloAcervo;
    public static javax.swing.JTextField txtTituloAcervo;
    public static javax.swing.JTextField txtVolumeAcervo;
    // End of variables declaration//GEN-END:variables

    //GET para os campos e botões do formulário para uso do ControllerEmprestimos
    public JTextField getTxtAutores_Id() {
        return txtAutores_Id;
    }

    public JTextField getTxtAutorNome() {
        return txtAutorNome;
    }

    public JButton getBtnSalvar() {
        return btnSalvar;
    }

    public JTextField getTxtLeitores_Id() {
        return txtLeitores_Id;
    }

    public JTextField getTxtAcervo_Id() {
        return txtAcervo_Id;
    }

    public JTextField getTxtDevolucao() {
        return txtDevolucao;
    }

    public JTextField getTxtNomeLeitores() {
        return txtNomeLeitores;
    }

    public JTextField getTxtTituloAcervo() {
        return txtTituloAcervo;
    }

    public JTextField getTxtSubTituloAcervo() {
        return txtSubTituloAcervo;
    }

    public JTextField getTxtExemplarAcervo() {
        return txtExemplarAcervo;
    }

    public JTextField getTxtEdicaoAcervo() {
        return txtEdicaoAcervo;
    }

    public JTextField getTxtVolumeAcervo() {
        return txtVolumeAcervo;
    }

    public JTextField getTxtLocalAcervo() {
        return txtLocalAcervo;
    }

    public JTextField getTxtDisponivelAcervo() {
        return txtDisponivelAcervo;
    }

    public JTable getTbEmprestimos() {
        return tbEmprestimos;
    }

    /**
     * Método que linka o AbstractTableModel a tabela no formulário
     * setTbEmprestimos
     *
     * @param modelo vindo de ControllerEmprestimos.carregar() com a lista do
     * TableModel
     */
    public void setTbEmprestimos(AbstractTableModel modelo) {
        this.tbEmprestimos.setModel(modelo);
        this.tbEmprestimos.setAutoResizeMode(JTable.AUTO_RESIZE_OFF);
        this.tbEmprestimos.setSelectionBackground(Color.cyan);  //Põe cor azul na linha atual
        this.tbEmprestimos.setSelectionForeground(Color.red);   //Põe letras em vermelho
        this.tbEmprestimos.setBackground(Color.lightGray);      //põe cor de fundo azul
        this.tbEmprestimos.getColumnModel().getColumn(0).setPreferredWidth(70); //Largura da coluna
        this.tbEmprestimos.getColumnModel().getColumn(0).setResizable(true);    //Coluna redimenciosavel
        this.tbEmprestimos.getColumnModel().getColumn(1).setPreferredWidth(200);
        this.tbEmprestimos.getColumnModel().getColumn(1).setResizable(true);
        this.tbEmprestimos.getColumnModel().getColumn(2).setPreferredWidth(200);
        this.tbEmprestimos.getColumnModel().getColumn(2).setResizable(true);
        this.tbEmprestimos.getColumnModel().getColumn(3).setPreferredWidth(80);
        this.tbEmprestimos.getColumnModel().getColumn(3).setResizable(true);
        this.tbEmprestimos.getColumnModel().getColumn(4).setPreferredWidth(60);
        this.tbEmprestimos.getColumnModel().getColumn(4).setResizable(true);
        this.tbEmprestimos.getColumnModel().getColumn(5).setPreferredWidth(60);
        this.tbEmprestimos.getColumnModel().getColumn(5).setResizable(true);
        this.tbEmprestimos.getColumnModel().getColumn(6).setPreferredWidth(150);
        this.tbEmprestimos.getColumnModel().getColumn(6).setResizable(true);
        this.tbEmprestimos.getColumnModel().getColumn(7).setPreferredWidth(90);
        this.tbEmprestimos.getColumnModel().getColumn(7).setResizable(true);
    }

    /**
     * Este método configura o titulo da ViewEmprestimos, de acordo com a
     * disponibilidade de itens no acervo.
     */
    private void tituloViewDevolucoes() {
        try {
            Connection conn = CriarConexao.abrirConexao();
            String SQL = "SELECT * FROM acervo WHERE Disponivel = 'não'";
            Statement stm = conn.createStatement();
            ResultSet rs = stm.executeQuery(SQL);
            if (rs.next()) {
                lblTitulo.setText("ESCOLHA UM ITEM DO ACERVO PARA DEVOLUÇÃO");
            } else {
                lblTitulo.setText("NÃO EXISTEM ITENS A SEREM DEVOLVIDOS");
                btnSalvar.setEnabled(false);
            }
        } catch (ClassNotFoundException | SQLException ex) {
            ex.printStackTrace();
        }
    }
}
